'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),World=require('../world-engine'),D=require('../data');
const copy=x=>JSON.parse(JSON.stringify(x));
const make=(heroes)=>{const e=new World(copy(D));assert(e.command('create',{stats:{strength:7,precision:7,charisma:7,knowledge:7},heroes}).ok);return e;};
const custom=[{name:'Roland',archetypeId:'guardian'},{name:'Elowen',archetypeId:'mage'},{name:'Robin',archetypeId:'ranger'}];
function piece(e,id,q=60){return{id:e._id('item'),recipeId:id,quality:q,affixId:null,enchantmentId:null,createdAt:0,makerGeneration:1,displayed:true,protected:false,reservedFor:null};}
function outfit(e,h,tier=1,variant=1){const pref=e.data.archetypes[h.archetypeId].preferences;for(const slot of Object.keys(h.equipment)){const r=Object.values(e.data.recipes).find(r=>r.slot===slot&&r.tier===tier&&r.variant===variant&&pref.includes(r.classId));if(r)h.equipment[slot]=piece(e,r.id);}if(e.data.recipes[h.equipment.weapon?.recipeId]?.twoHanded)h.equipment.offhand=null;}
test('creation accepts names/classes, saves them and limits actual purchases to class equipment',()=>{const e=make(custom);assert.deepEqual(e.state.adventurers.map(h=>[h.name,h.archetypeId]),custom.map(h=>[h.name,h.archetypeId]));assert(e.availableClasses().includes('cloth_armor'));const mage=e.state.adventurers.find(h=>h.archetypeId==='mage');mage.budget=999;for(const id of ['bronze_armor','bronze_leather_armor','bronze_cloth_armor'])e.state.inventory.push(piece(e,id));assert(!e.salePreview(e.state.inventory[0].id,mage.id).compatible);assert(!e.salePreview(e.state.inventory[1].id,mage.id).compatible);assert(e.salePreview(e.state.inventory[2].id,mage.id).compatible);const restored=new World(copy(D),e.exportSave());assert.deepEqual(restored.state.world.heroChoices,e.state.world.heroChoices);assert.equal(restored.state.adventurers[1].name,'Elowen');});
test('invalid or duplicate starting hero names cannot partially create a smith',()=>{const e=new World(copy(D));for(const heroes of [[custom[0],custom[0],custom[1]],[{...custom[0],name:'<script>'},custom[1],custom[2]]]){assert(!e.command('create',{stats:{strength:7,precision:7,charisma:7,knowledge:7},heroes}).ok);assert(!e.state.started);assert.equal(e.state.adventurers.length,0);}});
test('recruitment opens an empty paid charter, waits for name/class and spawns exactly one hero',()=>{const e=make();e.state.stats.questsLost=4;assert(e.command('tree',{id:'adventurers_recruitment_0'}).ok);e.tick(60000);assert.equal(e.state.adventurers.length,3);assert(!e.availableClasses().includes('foci'));assert(e.command('recruitHero',{id:'bren',name:'Merlin',archetypeId:'mage'}).ok);assert(e.availableClasses().includes('foci'));assert.equal(e.state.adventurers.length,4);assert(!e.command('recruitHero',{id:'bren',name:'Second',archetypeId:'breaker'}).ok);assert(World.validateSave(e.exportSave(),e.data).ok);});
test('stamina scales real employee effects, only time off restores it, and storage remains physical',()=>{const e=make();e.state.player.level=4;e.state.player.gold=1000;for(const staffId of ['apprentice','quartermaster'])assert(e.command('hireStaff',{staffId}).ok);const fresh=e._effects().speed,capacity=e.binCapacity();e.tick(25*60000);assert(Math.abs(e.state.staff.apprentice.stamina-50)<.001);assert.equal(e.staffEfficiency('apprentice'),.75);assert(e._effects().speed<fresh);e.tick(26*60000);assert.equal(e.staffEfficiency('apprentice'),0);assert.equal(e.state.staff.apprentice.stamina,0);assert.equal(e.binCapacity(),capacity);e.command('toggleStaff',{staffId:'apprentice'});e.command('toggleStaff',{staffId:'quartermaster'});e.tick(10*60000);assert.equal(e.state.staff.apprentice.stamina,100);assert.equal(e.staffEfficiency('apprentice'),0);assert.equal(e.binCapacity(),capacity);e.command('toggleStaff',{staffId:'apprentice'});assert.equal(e.staffEfficiency('apprentice'),1);assert.equal(e._effects().speed,fresh);});
test('employees learn only from matching work performed while effective; experience survives reload',()=>{const e=make();e.state.player.level=4;e.state.player.gold=1000;e.command('hireStaff',{staffId:'apprentice'});e._staffXp('craft',30);assert.equal(e.state.staff.apprentice.level,2);e.command('toggleStaff',{staffId:'apprentice'});e._staffXp('craft',500);assert.equal(e.state.staff.apprentice.level,2);e.command('toggleStaff',{staffId:'apprentice'});e.state.staff.apprentice.stamina=0;e._staffXp('craft',500);assert.equal(e.state.staff.apprentice.level,2);const f=new World(copy(D),e.exportSave());assert.equal(f.state.staff.apprentice.level,2);assert.equal(f.state.staff.apprentice.stamina,0);});
test('new patterns have coherent increasing costs, quality and prestige gates beyond the next tier',()=>{const e=make();assert.equal(Object.keys(e.data.classes).length,17);assert.equal(Object.keys(e.data.recipes).length,255);for(const c of Object.keys(e.data.classes))for(let tier=1;tier<=5;tier++){const rs=Object.values(e.data.recipes).filter(r=>r.classId===c&&r.tier===tier).sort((a,b)=>a.variant-b.variant);assert.equal(rs.length,3);assert(rs[0].basePrice<rs[1].basePrice&&rs[1].basePrice<rs[2].basePrice);assert(rs[0].qualityOffset<rs[1].qualityOffset&&rs[1].qualityOffset<rs[2].qualityOffset);assert(rs[2].requires.statValue>rs[1].requires.statValue*2);if(tier<5){const next=Object.values(e.data.recipes).find(r=>r.classId===c&&r.tier===tier+1&&r.variant===0);assert(rs[2].requires.statValue>next.requires.statValue);assert(rs[2].requires.proficiency>next.requires.proficiency);}}assert.equal(e.seams()[0].id,'fuel');assert.equal(Object.keys(e.data.decor).length,6);});
test('strict formations protect both rear lines; multi-round replays remain deterministic after reload',()=>{const e=make(custom);for(const h of e.state.adventurers)outfit(e,h);const q=e.data.quests.smuggler_cache,result=e._simulate(q,e.state.adventurers,12345),again=new World(copy(D),e.exportSave())._simulate(q,e.state.adventurers,12345);assert.deepEqual(result,again);assert.equal(result.rounds,3);let backTargets=0;for(const event of result.events.filter(x=>x.type==='attack'&&x.targetLine==='back')){backTargets++;const side=event.heroes.some(h=>h.id===event.targetId)?event.heroes:event.enemies;assert(side.filter(u=>u.line==='front').every(u=>u.hp<=0));}assert(backTargets>0);assert(result.events.some(x=>x.type==='round'&&x.round>1));assert(result.events.length<=800);});
test('ordinary wins add party contributions toward5, bosses stay one clear, and journeys are mostly battle',()=>{const e=make();e.state.upgrades.guild_hall=2;assert(e.command('dispatch',{questId:'rat_nest',heroIds:e.state.adventurers.map(h=>h.id)}).ok);const run=e.state.runs.at(-1);assert((run.battleEndAt-run.battleAt)/(run.returnAt-run.startAt)>.8);run.result.victory=true;e.state.simTime=run.returnAt;e._return(run);assert.equal(e.state.questWins.rat_nest,3);assert.equal(e.state.stats.questsWon,1);e._return(run);assert.equal(e.state.questWins.rat_nest,3);e.state.questWins.rat_nest=4;assert(!e._gates(e.data.quests.mill_cellar.requires).every(g=>g.met));e.state.questWins.rat_nest=5;assert(e._gates(e.data.quests.mill_cellar.requires).every(g=>g.met));});
test('ordinary quest pressure rises with mastery and stops increasing after5',()=>{const e=make(),q=e.data.quests.rat_nest;let r=e._simulate(q,e.state.adventurers,55),initial=r.enemyStats[0].health;e.state.questWins.rat_nest=5;r=e._simulate(q,e.state.adventurers,55);assert(r.enemyStats[0].health>initial);const full=r;e.state.questWins.rat_nest=1000;assert.deepEqual(e._simulate(q,e.state.adventurers,55),full);});
test('older campaign saves migrate missing proficiency, company identities and employee stamina once',()=>{const raw=fs.readFileSync('design/qa/campaign-preview-save.json','utf8');const e=new World(copy(D),raw);assert.equal(e.state.world.companyVersion,3);assert(e.state.player.proficiency.cloth_armor);assert.equal(Object.keys(e.state.world.heroChoices).length,3);const again=new World(copy(D),e.exportSave());assert.deepEqual(again.state.player.proficiency,e.state.player.proficiency);assert(World.validateSave(again.exportSave(),again.data).ok);});

test('old in-progress orders refund their old escrow after pattern costs change',()=>{const e=make();assert(e.command('craft',{recipeId:'bronze_swords'}).ok);const old=JSON.parse(e.exportSave()),job=old.state.jobs[0],escrow=e.data.legacyRecipeInputs[job.recipeId];job.inputs=copy(escrow);delete old.state.world.companyVersion;delete old.state.world.heroChoices;for(const id of Object.keys(escrow))old.state.materials[id]=0;const restored=new World(copy(D),old);assert(restored.command('cancel',{jobId:job.id}).ok);for(const[id,n]of Object.entries(escrow))assert.equal(restored.state.materials[id],n);assert(!restored.command('cancel',{jobId:job.id}).ok);});

test('staff stamina and effects follow the same clock online, offline, and after resting reload',()=>{const e=make();e.state.player.level=4;e.state.player.gold=1000;e.command('hireStaff',{staffId:'apprentice'});e.state.staff.apprentice.stamina=72;const f=new World(copy(D),e.exportSave());e.tick(120000,{offline:true});for(let i=0;i<120;i++)f.tick(1000);assert.deepEqual(e.state.staff,f.state.staff);assert.equal(e.staffEfficiency('apprentice'),.75);e.command('toggleStaff',{staffId:'apprentice'});const rested=new World(copy(D),e.exportSave());rested.tick(300000,{offline:true});assert.equal(rested.state.staff.apprentice.stamina,100);assert(!rested.state.staff.apprentice.active);assert.equal(rested.staffEfficiency('apprentice'),0);});

test('costly new furnishings grant real recovery and learning effects and survive Legacy',()=>{const e=make();e.state.player.level=4;e.state.player.gold=10000;e.command('hireStaff',{staffId:'apprentice'});e.command('toggleStaff',{staffId:'apprentice'});e.state.staff.apprentice.stamina=0;const gold=e.state.player.gold;for(const decorId of ['rest_chamber','guild_library'])assert(e.command('decorate',{decorId}).ok);assert.equal(gold-e.state.player.gold,4300);assert.equal(e._effects().proficiencyXp,.2);e.tick(60000);assert(Math.abs(e.state.staff.apprentice.stamina-15)<.001);e.state.questWins.void_sovereign=1;assert(e.command('retire',{confirmed:true}).ok);assert.deepEqual(e.state.decorations,['rest_chamber','guild_library']);assert.deepEqual(e.state.staff,{});});
