'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),World=require('../world-engine'),D=require('../data'),P=require('../progression');
const make=()=>{const e=new World(JSON.parse(JSON.stringify(D)));assert(e.command('create',{stats:{strength:7,precision:7,charisma:7,knowledge:7}}).ok);return e;};
function fullDiscount(e){e.state.upgrades.supply_logistics=4;e.state.staff.quartermaster={level:5,active:true,xp:0};e.state.player.talents=['trade_network'];for(let i=0;i<=5;i++)e.state.world.trees['mine_logistics_'+i]=i===5?4:1;}
test('Legacy depth costs are exponential and the complete tree costs304 sparks',()=>{const e=make();assert.deepEqual(Object.values(e.data.talents).slice(0,6).map(t=>t.cost),[2,4,7,11,19,33]);assert.equal(Object.values(e.data.talents).reduce((n,t)=>n+t.cost,0),304);});
test('Legacy requires the tier5 boss and rewards distinct boss difficulty',()=>{const e=make();e.state.player.level=50;e.state.stats.questsWon=100000;e.state.questWins={rat_nest:100000};assert.equal(e.derived().legacyReward,0);assert(!e.derived().legacyEligible);assert(!e.command('retire',{confirmed:true}).ok);e.state.player.level=12;for(const id of e.data.tierBosses)e.state.questWins[id]=1;assert.equal(e.derived().legacyReward,46);assert(e.derived().legacyEligible);e.state.questWins.void_sovereign=99999;assert.equal(e.derived().legacyReward,46);e.state.player.level=24;assert.equal(e.derived().legacyReward,48);assert.deepEqual(e.retirementPreview().breakdown,e.derived().legacyBreakdown);});
test('one full campaign buys a meaningful subset of Legacy and old sparks/talents survive',()=>{const e=make();e.state.player.level=12;e.state.stats.questsWon=5;for(const id of e.data.tierBosses)e.state.questWins[id]=1;assert(e.command('retire',{confirmed:true}).ok);assert.equal(e.state.player.legacy.totalPoints,46);for(const t of Object.values(e.data.talents))if(e.talentPreview(t.id).eligible)e.command('talent',{talentId:t.id});assert(e.state.player.talents.length>0&&e.state.player.talents.length<24);e.state.player.legacy.points=700;e.state.player.legacy.totalPoints+=700;const restored=new World(JSON.parse(JSON.stringify(D)),e.exportSave());assert.equal(restored.state.player.legacy.points,700);assert.deepEqual(restored.state.player.talents,e.state.player.talents);});
test('all common materials and batch sizes1–30 lose money on immediate resale, including maximum legitimate discounts',()=>{for(const discount of [false,true]){const e=make();if(discount)fullDiscount(e);for(const m of Object.values(e.data.materials).filter(m=>Number.isFinite(m.price)))for(let qty=1;qty<=30;qty++){const sale=e.materialSalePrice(m.id,qty);assert(Number.isSafeInteger(sale)&&sale>=0);assert(sale<e.materialPrice(m.id)*qty,m.id+' quantity '+qty);}}});
test('raw-sale quotes match execution; bulk and split sales cannot manufacture coins',()=>{const e=make();e.state.materials.wood=20;const gold=e.state.player.gold;assert.equal(e.materialSalePrice('wood',1),0);assert.equal(e.materialSalePrice('wood',10),5);assert(e.command('sellMaterial',{materialId:'wood',quantity:10}).ok);assert.equal(e.state.player.gold,gold+5);for(let i=0;i<10;i++)assert(e.command('sellMaterial',{materialId:'wood',quantity:1}).ok);assert.equal(e.state.player.gold,gold+5);assert.equal(e.materialSalePrice('ember_shard',1),null);});
test('clearance offers remain below customer value and current replacement inputs at every tier',()=>{for(const discount of [false,true]){const e=make();if(discount)fullDiscount(e);for(const recipe of Object.values(e.data.recipes))for(const quality of [1,50,100,200]){const item={id:e._id('item'),recipeId:recipe.id,quality};e.state.inventory.push(item);const input=Object.entries(recipe.inputs).reduce((n,[id,qty])=>n+(e.materialPrice(id)||0)*qty,0),offer=e.salePreview(item.id).price;assert(offer<e.itemPrice(item.id),recipe.id+' NPC premium');assert(offer<input,recipe.id+' liquidation loop');e.state.inventory.pop();}}});
test('paid Quartermaster and migrated material warehouses increase actual per-bin storage',()=>{const e=make();const before=e.binCapacity();e.state.player.level=3;e.state.player.gold=1000;assert(e.command('hireStaff',{staffId:'quartermaster'}).ok);assert.equal(e.binCapacity(),before+3);e.state.staff.quartermaster.level=5;assert.equal(e.binCapacity(),before+15);e.state.upgrades.material_warehouse=2;assert.equal(e.binCapacity(),before+23);});
test('all96 room nodes and worker hires have positive exponentially escalating prices',()=>{const e=make();assert.equal(Object.keys(P.nodes).length,96);for(const n of Object.values(P.nodes)){let previous=0;for(let rank=0;rank<n.maxRank;rank++){e.state.world.trees[n.id]=rank;const cost=e.treePreview(n.id).cost;assert(Number.isSafeInteger(cost)&&cost>previous,n.id);previous=cost;}}e.state.world.miners=Array.from({length:10},(_,i)=>({id:'miner-'+i}));assert.equal(e.hireCost(),31);e.state.world.miners=Array.from({length:28},(_,i)=>({id:'miner-'+i}));assert.equal(e.hireCost(),1716);});
