'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const World=require('../world-engine'),D=require('../data'),P=require('../progression');
const copy=x=>JSON.parse(JSON.stringify(x));
function make(mage=false){const e=new World(copy(D));e.command('create',{stats:{strength:7,precision:7,charisma:7,knowledge:7},...(mage?{heroes:[{name:'Ada',archetypeId:'mage'},{name:'Rory',archetypeId:'guardian'},{name:'Gwen',archetypeId:'ranger'}]}:{})});return e;}
function advanced(e){e.state.player.level=15;e.state.player.gold=1000;for(const id of Object.keys(e.state.player.stats))e.state.player.stats[id]=100;for(const p of Object.values(e.state.player.proficiency))p.level=100;for(let i=0;i<=4;i++)e.state.world.trees['forge_machinery_'+i]=1;for(const id of Object.keys(e.state.materials))e.state.materials[id]=e.binCapacity();e.state.unlocks.recipes=Object.keys(e.data.recipes);}
const item=(e,recipeId,quality=80,more={})=>({id:e._id('item'),recipeId,quality,makerGeneration:1,...more});

test('purchased oil is required only for tiers3–5, cannot be mined, and applying content is idempotent',()=>{const e=make();assert.equal(e.materialPrice('alchemical_oil'),8);assert(e.materialAvailable('alchemical_oil'));assert(!e.seams().some(s=>s.id==='alchemical_oil'));assert(!e.command('mine',{materialId:'alchemical_oil'}).ok);for(const r of Object.values(e.data.recipes))assert.equal(r.inputs.alchemical_oil,r.tier>=3?r.tier-2+(r.variant===2?1:0):undefined);e.state.inventory.push(item(e,'starforged_swords_v2'));assert(e.command('salvage',{itemId:e.state.inventory[0].id}).ok);assert.equal(e.state.materials.alchemical_oil,0);const before=JSON.stringify(e.data);P.apply(e.data);assert.equal(JSON.stringify(e.data),before);});

test('oil purchases, advanced crafting and cancellation account for real materials and gold',()=>{const e=make();advanced(e);e.state.materials.alchemical_oil=0;assert(!e.craftPreview('steel_swords').eligible);const gold=e.state.player.gold;assert(e.command('buyMaterial',{materialId:'alchemical_oil',quantity:1}).ok);assert.equal(e.state.player.gold,gold-8);assert(e.command('craft',{recipeId:'steel_swords'}).ok);const job=e.state.jobs.at(-1);assert.equal(job.inputs.alchemical_oil,1);assert.equal(e.state.materials.alchemical_oil,0);assert(e.command('cancel',{jobId:job.id}).ok);assert.equal(e.state.materials.alchemical_oil,1);assert(!e.command('cancel',{jobId:job.id}).ok);e.state.materials.alchemical_oil=e.binCapacity();const before=e.state.player.gold;assert(!e.command('buyMaterial',{materialId:'alchemical_oil',quantity:1}).ok);assert.equal(e.state.player.gold,before);});

test('old supply-free orders and saves migrate without inventing an oil refund',()=>{const e=make();advanced(e);assert(e.command('craft',{recipeId:'steel_swords'}).ok);const save=JSON.parse(e.exportSave()),job=save.state.jobs[0];job.inputs=copy(e.data.preSupplyRecipeInputs[job.recipeId]);delete save.state.materials.alchemical_oil;for(const id of Object.keys(job.inputs))save.state.materials[id]=0;const restored=new World(copy(D),save);assert.equal(restored.state.materials.alchemical_oil,0);assert(restored.command('cancel',{jobId:job.id}).ok);assert.equal(restored.state.materials.alchemical_oil,0);for(const[id,n]of Object.entries(job.inputs))assert.equal(restored.state.materials[id],n);assert(World.validateSave(restored.exportSave(),restored.data).ok);});

test('hero forge suggestions are read-only, class-compatible and match the actual purchase comparison',()=>{const e=make(true),h=e.state.adventurers[0],before=e.exportSave(),v=e.heroForgeOptions(h.id);assert.deepEqual(e.exportSave(),before);assert(v.classes.includes('cloth_armor'));assert(!v.classes.includes('armor'));assert(v.rows.some(r=>r.classId==='foci'&&r.ready));assert(!v.rows.some(r=>e.data.recipes[r.recipeId].tier>1||e.data.recipes[r.recipeId].variant!==0));for(const row of v.rows){const i=item(e,row.recipeId,row.quality);e.state.inventory.push(i);const sale=e.salePreview(i.id,h.id);assert(sale.compatible);assert.equal(sale.improvement,row.improvement);assert.equal(sale.price,row.price);e.state.inventory.pop();}});

test('suggestions separate shortages and queue limits, and reject downgrades to strong enchanted gear',()=>{const e=make(),h=e.state.adventurers[0];e.state.materials.leather=0;let v=e.heroForgeOptions(h.id);const sword=v.rows.find(r=>r.recipeId==='bronze_swords');assert(sword&&!sword.ready);assert(sword.shortages.some(s=>s.id==='leather'));assert(!v.rows.some(r=>r.recipeId==='bronze_swords_v1'));for(const slot of Object.keys(h.equipment)){const r=Object.values(e.data.recipes).find(r=>r.tier===5&&r.variant===2&&r.slot===slot&&e.data.archetypes[h.archetypeId].preferences.includes(r.classId));if(r)h.equipment[slot]=item(e,r.id,200);}assert.equal(e.heroForgeOptions(h.id).rows.length,0);const full=make();for(let i=0;i<6;i++){full.state.materials.bronze=10;full.state.materials.leather=10;full.state.materials.fuel=10;full.command('craft',{recipeId:'bronze_swords'});}assert(full.heroForgeOptions(full.state.adventurers[0].id).rows.every(r=>!r.ready));});

test('offhand recommendations respect two-handed gear and include the cost of losing an equipped offhand',()=>{const e=make(true);advanced(e);const h=e.state.adventurers[0];h.equipment.weapon=item(e,'bronze_foci_v2');assert(e.heroForgeOptions(h.id).offhandBlocked);assert(!e.heroForgeOptions(h.id).rows.some(r=>r.slot==='offhand'));h.equipment.weapon=item(e,'bronze_foci');h.equipment.offhand=item(e,'bronze_offhands');const row=e.heroForgeOptions(h.id).rows.find(r=>r.recipeId==='steel_foci_v2');assert(row?.removesOffhand);const candidate=copy(h);candidate.equipment.weapon=item(e,row.recipeId,row.quality);candidate.equipment.offhand=null;const q=e.data.quests.rat_nest;assert.equal(row.improvement,e._gearScore(candidate,q)-e._gearScore(h,q));});

test('hero combat summary uses final equipment/training stats and actual level experience thresholds',()=>{const e=make(),h=e.state.adventurers[0];h.equipment.weapon=item(e,'bronze_swords_v1');e.state.world.trees.adventurers_training_0=1;e.state.world.trees.adventurers_training_1=1;e._heroXp(h,24);let v=e.heroCombatSummary(h.id);assert.equal(v.experience,24);assert.equal(v.experienceRequired,25);assert.deepEqual(v.stats,e.heroStats(h.id));assert.equal(v.expectedDps,v.stats.attack*(1+.5*v.stats.crit)/v.stats.interval);e._heroXp(h,1);v=e.heroCombatSummary(h.id);assert.equal(h.level,2);assert.equal(v.experience,0);assert.equal(v.experienceRequired,50);h.level=30;assert(e.heroCombatSummary(h.id).maxLevel);});

test('active combat stat cards use the dispatched party snapshot and replay health',()=>{const e=make();e.state.upgrades.guild_hall=2;const h=e.state.adventurers[0];assert(e.command('dispatch',{questId:'rat_nest',heroIds:e.state.adventurers.map(h=>h.id)}).ok);const run=e.state.runs.at(-1);e.state.world.trees.adventurers_training_1=4;e.state.simTime=run.battleAt+1000;const v=e.heroCombatSummary(h.id);assert(v.inExpedition);assert.deepEqual(v.stats,run.result.heroStats.find(u=>u.id===h.id));assert.equal(v.currentHealth,e.battleView(run.id).heroes.find(u=>u.id===h.id).hp);assert.notEqual(v.stats.attack,e.heroStats(h.id).attack);});
