'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const W=require('../world-engine'),D=require('../data'),P=require('../progression'),C=require('../campaign');
const clone=x=>JSON.parse(JSON.stringify(x));
function create(){const e=new W(clone(D));assert(e.command('create',{name:'Idle review',profession:'weaponsmith',stats:{strength:7,precision:7,charisma:7,knowledge:7}}).ok);return e;}
function play(minutes,passive=false){const e=create(),milestones={},history=[],bossAttempts=[],validationErrors=[],failures={};let decisions=0,maxOverdue=0;
const act=(a,p={})=>{const r=e.command(a,p);if(!r.ok)failures[a+': '+r.message]=(failures[a+': '+r.message]||0)+1;return r;};
const stamp=(k,v)=>{if(v&&milestones[k]==null)milestones[k]=+(e.state.simTime/60000).toFixed(2);};
for(let t=0;t<minutes*60000;t+=30000){if(!passive){
 while(e.state.player.points>0)act('allocate',{stat:['precision','knowledge','strength'][decisions++%3]});
 const seams=e.seams(),demand=seams.filter(s=>['bronze','fuel','iron','steel','mithril'].includes(s.id)).sort((a,b)=>e.state.materials[a.id]-e.state.materials[b.id]);
 if(demand.length&&e.state.materials[demand[0].id]<e.binCapacity())act('mine',{materialId:demand[0].id});
 for(const id of ['wood','leather'])if(e.state.materials[id]<4&&e.state.player.gold>=8)act('buyMaterial',{materialId:id,quantity:4-e.state.materials[id]});
 if(e.state.world.miners.length<4&&e.currencies().mine>=e.hireCost()&&e.state.world.miners.length<e.derived().workerCapacity)act('hireMiner');
 for(let i=0;i<e.state.world.miners.length;i++){const m=e.state.world.miners[i],id=i===1?'fuel':i===2&&seams.some(s=>s.id==='iron')?'iron':i===3&&seams.some(s=>s.id==='steel')?'steel':'bronze';if(m.assigned!==id)act('assignWorker',{id:m.id,materialId:id});}
 const priorities=['mine_extraction_0','mine_logistics_0','mine_depths_0','mine_extraction_1','mine_logistics_1','mine_extraction_2','mine_depths_1','mine_depths_2','mine_extraction_3','mine_logistics_2','mine_logistics_3','mine_depths_3','forge_machinery_0','forge_machinery_1','forge_workflow_0','forge_workflow_1','forge_mastery_0','forge_machinery_2','forge_machinery_3','forge_workflow_2','forge_mastery_1','forge_mastery_2','forge_mastery_3','shop_warehouse_0','shop_commerce_0','shop_warehouse_1','shop_commerce_1','shop_commerce_2','adventurers_training_0','adventurers_training_1','adventurers_expeditions_0','adventurers_expeditions_1','adventurers_expeditions_2','adventurers_expeditions_3','adventurers_expeditions_4','adventurers_training_2','adventurers_training_3','adventurers_recruitment_0'];
 for(const id of priorities)if(!e.state.world.trees[id]&&e.treePreview(id).eligible&&(P.nodes[id].section!=='forge'||e.state.player.gold>e.treePreview(id).cost+12))act('tree',{id});
 for(const item of [...e.state.inventory])if(!item.protected&&!item.reservedFor&&(e.state.inventory.filter(i=>i.recipeId===item.recipeId).length>1||e.state.simTime-item.createdAt>600000))act('sell',{itemId:item.id});
 const count=r=>e.state.inventory.filter(i=>i.recipeId===r.id).length+e.state.jobs.filter(j=>j.recipeId===r.id).length;
 const recipes=Object.values(e.data.recipes).filter(r=>e._recipeKnown(r)&&['swords','daggers','bows','armor','shields'].includes(r.classId));
 recipes.sort((a,b)=>count(a)-count(b)||b.tier-a.tier||a.variant-b.variant||a.id.localeCompare(b.id));
 const r=recipes.find(r=>count(r)<1&&e.craftPreview(r.id).eligible);if(r)act('craft',{recipeId:r.id});
 for(const j of e.state.jobs)if(j.status==='active'&&!j.technique)act('technique',{jobId:j.id});
 for(const s of e.seams())if(e.state.materials[s.id]>e.binCapacity()-5)act('sellMaterial',{materialId:s.id,quantity:8});
 const target=C.bosses.find(id=>!e.state.questWins[id]);
 if(target&&!e.state.runs.some(run=>run.questId===target&&!run.rewardApplied)&&e._gates(e.data.quests[target].requires).every(g=>g.met)){
 const ids=e.state.adventurers.slice(0,3).map(h=>h.id);
 if(!e.state.world.bossTarget&&ids.length>=e.data.quests[target].minPartySize)act('prepareBoss',{questId:target,heroIds:ids});
 if(e.state.world.bossTarget){const preview=e.questPreview(target,e.state.world.bossParty);if(preview.eligible&&preview.successEstimate>=65){const p=[...e.state.world.bossParty];const launched=act('launchBoss',{questId:target,heroIds:p});if(launched.ok)bossAttempts.push({minute:e.state.simTime/60000,quest:target,estimate:preview.successEstimate});}else if(preview.eligible&&preview.successEstimate<65)act('releaseBoss');}
 }
}
e.tick(30000);stamp('firstCraft',e.state.stats.crafted);stamp('firstSale',e.state.stats.sold);stamp('firstVictory',e.state.stats.questsWon);stamp('level2',e.state.player.level>=2);for(const id of C.bosses)stamp(id,e.state.questWins[id]);
maxOverdue=Math.max(maxOverdue,e.state.runs.filter(r=>r.status!=='complete'&&r.returnAt<e.state.simTime-1000).length);
if(t%1800000===0){const valid=W.validateSave(e.exportSave(),e.data);if(!valid.ok)validationErrors.push({minute:e.state.simTime/60000,message:valid.message});history.push({minute:e.state.simTime/60000,level:e.state.player.level,gold:e.state.player.gold,crafted:e.state.stats.crafted,wins:e.state.stats.questsWon,losses:e.state.stats.questsLost});}
}
assert.equal(validationErrors.length,0,'Normal play must produce reloadable saves');assert.equal(maxOverdue,0);assert.equal(Object.values(e.state.questCargo).reduce((a,b)=>a+b,0),0);assert(!e.state.mailbox.length);
return{minutes,policy:passive?'Unattended with empty shop':'30-second active manager; 5 useful classes; material sales; first-rank upgrades; boss launch at >=65% estimated chance',milestones,bossAttempts,level:e.state.player.level,gold:e.state.player.gold,crafted:e.state.stats.crafted,sold:e.state.stats.sold,wins:e.state.stats.questsWon,losses:e.state.stats.questsLost,questWins:e.state.questWins,heroLevels:e.state.adventurers.map(h=>({name:h.name,level:h.level,status:h.status,gear:Object.values(h.equipment).filter(Boolean).length})),workers:e.state.world.miners.length,highestCraftedTier:Math.max(0,...Object.keys(e.state.player.legacy.collection).map(id=>e.data.recipes[id].tier)),highestProficiency:Math.max(...Object.values(e.state.player.proficiency).map(p=>p.level)),materialsLost:e.state.world.materialsLost||0,trees:e.state.world.trees,legacy:e.retirementPreview(),maxOverdue,validationErrors,history,failedActions:failures};}
function fixtures(){const e=create(),checks=[];assert.equal(Object.keys(e.data.recipes).length,180);for(const c of Object.keys(e.data.classes))for(let t=1;t<=5;t++)assert.equal(Object.values(e.data.recipes).filter(r=>r.classId===c&&r.tier===t).length,3);
for(let t=2;t<=5;t++)for(const q of Object.values(e.data.quests).filter(q=>q.tier===t))assert(q.requires.questWins[C.bosses[t-2]]>=1);
checks.push('180 recipes; exactly 3 patterns for every tier/class; every next-tier quest requires preceding tier boss.');
const edges=Object.values(e.data.quests).flatMap(q=>Object.keys(q.requires.questWins||{}).map(p=>[q.id,p]));function walk(id,stack=[]){assert(!stack.includes(id),'Quest prerequisite cycle');for(const [a,b]of edges)if(a===id)walk(b,[...stack,id]);}Object.keys(e.data.quests).forEach(id=>walk(id));checks.push('Quest prerequisite graph has no cycles.');
e.state.player.level=100;e.state.stats.questsWon=10000;assert.equal(e.retirementPreview().eligible,false);assert.equal(e.retirementPreview().sparks,0);assert(!e.command('retire',{confirmed:true}).ok);for(const id of C.bosses)e.state.questWins[id]=1;assert(e.retirementPreview().eligible);const reward=e.retirementPreview().sparks;e.state.questWins.void_sovereign=10000;assert.equal(e.retirementPreview().sparks,reward);checks.push('10,000 ordinary victories cannot retire; final boss permits retirement; repeated final boss kills do not farm sparks.');
const bossLoadouts=[];for(let t=1;t<=5;t++){const f=create();for(const id of Object.keys(f.data.quests))f.state.questWins[id]=10;f.state.world.trees.adventurers_expeditions_0=1;f.state.world.trees.adventurers_expeditions_1=1;f.state.world.trees.adventurers_expeditions_2=1;f.state.world.trees.adventurers_expeditions_3=1;f.state.world.trees.adventurers_expeditions_4=1;const heroes=f.state.adventurers;for(const h of heroes){h.status='ready';h.level=1+2*(t-1);for(const slot of Object.keys(h.equipment)){const recipe=Object.values(f.data.recipes).find(r=>r.tier===t&&r.slot===slot&&f.data.archetypes[h.archetypeId].preferences.includes(r.classId));if(recipe)h.equipment[slot]={recipeId:recipe.id,quality:45+10*(t-1)};}}const id=C.bosses[t-1],heroIds=heroes.map(h=>h.id);const preview=f.questPreview(id,heroIds);assert(f.command('prepareBoss',{questId:id,heroIds}).ok);assert(f.command('launchBoss',{questId:id,heroIds}).ok);const run=f.state.runs.at(-1);f.tick(run.returnAt-f.state.simTime);assert(run.rewardApplied);bossLoadouts.push({tier:t,heroLevel:1+2*(t-1),quality:45+10*(t-1),party:heroIds,estimatedWin:preview.successEstimate,actualVictory:run.result.victory});}checks.push('All 5 manual bosses accept selected ready parties and resolve normally with same-tier synthetic loadouts.');
const gathering=create();gathering.state.questWins.rat_nest=5;const gatheredIds=gathering.state.adventurers.map(h=>h.id);gathering.tick(60000);assert(gathering.state.adventurers.some(h=>h.status==='travelling'));assert(gathering.command('prepareBoss',{questId:'smuggler_cache',heroIds:gatheredIds}).ok);gathering.tick(600000);assert(gathering.state.adventurers.every(h=>['browsing','ready'].includes(h.status)));assert(gathering.command('launchBoss',{questId:'smuggler_cache',heroIds:gatheredIds}).ok);checks.push('Starter trio gathers through travel, defeat and recovery; all 3 launch despite regular party size1.');
const prices=Object.values(e.data.recipes).map(r=>{const p=e.craftPreview(r.id);const inputValue=Object.entries(p.inputs).reduce((v,[id,n])=>v+(e.data.materials[id].price||0)*n,0);return{id:r.id,tier:r.tier,basePrice:r.basePrice,quote:p.price,inputBuyValue:inputValue,townPrice:Math.max(1,Math.min(Math.floor(inputValue*.65),Math.floor(p.price*.55))),seconds:Math.round(p.seconds),margin:p.price-inputValue};});return{checks,bossLoadouts,legacyRewardFixture:reward,totalTalentCost:Object.values(e.data.talents).reduce((v,t)=>v+t.cost,0),pricingByTier:[1,2,3,4,5].map(t=>{const rows=prices.filter(r=>r.tier===t);return{tier:t,minMargin:Math.min(...rows.map(r=>r.margin)),maxMargin:Math.max(...rows.map(r=>r.margin)),negativeMargin:rows.filter(r=>r.margin<0).length,patterns:rows.length,townNegativeMargin:rows.filter(r=>r.townPrice<r.inputBuyValue).length};})};}
const result={generatedAt:new Date().toISOString(),reviewer:'AI reviewer using idle-game enthusiast lens',method:'Deterministic accelerated engine play, no state grants in player profiles. Fixture section explicitly grants wins/loadouts to isolate gates and combat; it does not prove full-campaign completion.',profiles:[play(240),play(480,true)],fixtures:fixtures()};fs.writeFileSync('design/qa/idle-enthusiast-v2.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,(k,v)=>['history','trees','legacy'].includes(k)?undefined:v,2));






