const test=require('node:test'),assert=require('node:assert/strict');
const World=require('../world-engine'),D=require('../data');
const make=()=>{const e=new World(JSON.parse(JSON.stringify(D)));assert(e.command('create',{stats:{strength:7,precision:7,charisma:7,knowledge:7}}).ok);return e;};
function returning(e){const hero=e.state.adventurers[0];assert(e.command('dispatch',{questId:'rat_nest',heroIds:[hero.id]}).ok);const run=e.state.runs.at(-1);run.result.victory=true;run.reward={materials:{bronze:4},gold:7,recipes:['iron_swords'],source:'Regression reward'};e.state.simTime=run.returnAt;return{hero,run};}
function full(e){for(const id of Object.keys(e.state.materials))e.state.materials[id]=e.binCapacity();e.state.mailbox=Array.from({length:25},(_,i)=>({id:'full-'+i,materials:{bronze:1},gold:1,recipes:[]}));}
test('returning heroes come home with full bins and full mailbox; currencies awarded once and excess materials discarded',()=>{const e=make(),{hero,run}=returning(e);full(e);const gold=e.state.player.gold;e._return(run);assert.equal(run.status,'complete');assert.equal(hero.status,'browsing');assert.equal(hero.runId,null);assert.equal(e.state.player.gold,gold+7);assert.equal(e.state.questCargo.bronze,undefined);assert.equal(e.state.world.materialsLost,4);assert(e.state.unlocks.recipes.includes('iron_swords'));e._return(run);assert.equal(e.state.player.gold,gold+7);assert.equal(e.state.questCargo.bronze,undefined);assert.equal(e.state.world.materialsLost,4);assert.equal(e.state.stats.questsWon,1);assert(World.validateSave(e.exportSave(),e.data).ok);});
test('old pending saves recover immediately on load without losing their quest reward',()=>{const e=make(),{hero,run}=returning(e);full(e);run.status='pending';hero.status='returning';const restored=new World(JSON.parse(JSON.stringify(D)),e.exportSave());assert.equal(restored.state.adventurers[0].status,'browsing');assert.equal(restored.state.runs.at(-1).status,'complete');assert.equal(restored.state.questCargo.bronze,undefined);const again=new World(JSON.parse(JSON.stringify(D)),restored.exportSave());assert.equal(again.state.stats.questsWon,1);assert.equal(again.state.player.gold,restored.state.player.gold);});
test('old quest cargo is delivered up to capacity once and excess is discarded on migration',()=>{const e=make();e.state.materials.bronze=e.binCapacity()-2;e.state.questCargo={bronze:5};const restored=new World(JSON.parse(JSON.stringify(D)),e.exportSave());assert.equal(restored.state.materials.bronze,restored.binCapacity());assert.equal(restored.state.world.materialsLost,3);assert.deepEqual(restored.state.questCargo,{});restored.command('sellMaterial',{materialId:'bronze',quantity:3});const again=new World(JSON.parse(JSON.stringify(D)),restored.exportSave());assert.equal(again.state.materials.bronze,again.binCapacity()-3);assert.equal(again.state.world.materialsLost,3);});
test('stale returning statuses with missing or completed runs are repaired without duplicate rewards',()=>{const e=make(),{hero,run}=returning(e);e._return(run);const gold=e.state.player.gold;hero.status='returning';hero.runId=run.id;e._reconcileAdventurers();assert.equal(hero.status,'browsing');assert.equal(hero.runId,null);hero.status='returning';hero.runId='missing';e.tick(1000);assert.equal(hero.status,'browsing');assert.equal(e.state.player.gold,gold);assert.equal(e.state.stats.questsWon,1);});
test('hero follow activity reports shop, outward journey, battle, homeward journey and recovery',()=>{const e=make(),h=e.state.adventurers[0];assert.equal(e.heroActivity(h.id).room,'shop');e.command('dispatch',{questId:'rat_nest',heroIds:[h.id]});const r=e.state.runs.at(-1);assert.equal(e.heroActivity(h.id).phase,'travelling');e.state.simTime=r.battleAt;assert.equal(e.heroActivity(h.id).phase,'fighting');e.state.simTime=r.battleEndAt;assert.equal(e.heroActivity(h.id).phase,'returning');assert(e.heroActivity(h.id).remainingMs>0);r.result.victory=false;e.state.simTime=r.returnAt;e._return(r);assert.equal(e.heroActivity(h.id).phase,'recovering');assert.equal(e.heroActivity(h.id).room,'adventurers');e.tick(h.recoverUntil-e.state.simTime);assert.equal(e.heroActivity(h.id).room,'shop');});
test('cargo validation rejects unsafe, negative and unknown material balances',()=>{for(const cargo of [{bronze:-1},{bronze:Number.MAX_SAFE_INTEGER+1},{bogus:1},[]]){const e=make(),save=JSON.parse(e.exportSave());save.state.questCargo=cargo;assert(!World.validateSave(save,e.data).ok);}});
test('repeated successful returns discard overflow without overflowing expedition history or blocking another trip',()=>{const e=make();full(e);const gold=e.state.player.gold;for(let i=0;i<50;i++){const {run,hero}=returning(e);e._return(run);assert.equal(hero.status,'browsing');}assert.deepEqual(e.state.questCargo,{});assert.equal(e.state.world.materialsLost,205);assert.equal(e.state.player.gold,gold+350);assert.equal(e.state.stats.questsWon,50);assert.equal(e.state.runs.length,16);assert.equal(e.state.mailbox.length,25);assert(World.validateSave(e.exportSave(),e.data).ok);});
