'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),World=require('../world-engine'),D=require('../data'),M=require('../room-model');
const make=()=>{const g=new World(JSON.parse(JSON.stringify(D)));g.command('create',{name:'Room QA',profession:'weaponsmith',stats:{strength:7,precision:7,charisma:7,knowledge:7}});return g;};
test('new and uncreated workshops always use the humble backgrounds',()=>{const g=make();for(const room of ['smith','mine','forge','shop','adventurers'])assert.equal(M.artKey(g,room),room+'-starter');g.state.started=false;g.state.player.level=100;assert.equal(M.artKey(g,'smith'),'smith-starter');});
test('middle scenes require the first boss and each room milestone',()=>{const g=make();g.state.player.level=8;g.state.world.trees.mine_depths_0=1;g.state.world.trees.forge_machinery_1=1;for(const r of ['smith','mine','forge'])assert.equal(M.stage(g,r),'starter');g.state.questWins.smuggler_cache=1;for(const r of ['smith','mine','forge'])assert.equal(M.stage(g,r),'middle');assert.equal(M.stage(g,'shop'),'starter');g.state.player.reputation=50;g.state.world.trees.shop_warehouse_0=2;assert.equal(M.stage(g,'shop'),'middle');g.state.stats.questsWon=25;assert.equal(M.stage(g,'adventurers'),'starter');g.state.adventurers.push({...g.state.adventurers[0],id:'fourth'});assert.equal(M.stage(g,'adventurers'),'middle');});
function late(){const g=make(),P=require('../progression');for(const n of Object.values(P.nodes))g.state.world.trees[n.id]=n.maxRank;g.state.player.level=30;g.state.player.reputation=1000;g.state.questWins.smuggler_cache=1;g.state.questWins.frost_citadel=1;g.state.stats.questsWon=300;while(g.state.adventurers.length<8)g.state.adventurers.push({...g.state.adventurers[0],id:'extra-'+g.state.adventurers.length});return g;}
test('first-life endgame keeps middle backgrounds; a deep second generation unlocks grand scenes',()=>{const g=late();for(const r of ['smith','mine','forge','shop','adventurers'])assert.equal(M.stage(g,r),'middle');g.state.player.legacy.generation=2;for(const r of ['smith','mine','forge','shop','adventurers'])assert.equal(M.artKey(g,r),r);delete g.state.questWins.frost_citadel;for(const r of ['smith','mine','forge','shop','adventurers'])assert.equal(M.stage(g,r),'middle');});
test('a fresh Legacy run starts humble and rooms still require their own late milestones',()=>{const g=make();g.state.player.legacy.generation=8;for(const r of ['smith','mine','forge','shop','adventurers'])assert.equal(M.stage(g,r),'starter');const l=late();l.state.player.legacy.generation=2;l.state.player.level=24;assert.equal(M.stage(l,'smith'),'middle');l.state.player.level=25;assert.equal(M.stage(l,'smith'),'grand');delete l.state.world.trees.mine_depths_4;assert.equal(M.stage(l,'mine'),'middle');delete l.state.world.trees.forge_machinery_4;assert.equal(M.stage(l,'forge'),'middle');l.state.player.reputation=499;assert.equal(M.stage(l,'shop'),'middle');l.state.stats.questsWon=199;assert.equal(M.stage(l,'adventurers'),'middle');});
test('all fifteen room stages have complete landscape PNG assets',()=>{const fs=require('node:fs'),path=require('node:path');for(const room of ['smith','mine','forge','shop','adventurers'])for(const suffix of ['-starter','-middle','']){const b=fs.readFileSync(path.join(__dirname,'../assets',room+suffix+'.png'));assert.equal(b.subarray(1,4).toString(),'PNG');assert(b.readUInt32BE(16)>=1024);assert(b.readUInt32BE(16)>b.readUInt32BE(20));}});
test('hero following tracks shop, outward journey, battle, return, recovery, and shopping again',()=>{const g=make(),h=g.state.adventurers[0];assert.equal(M.followRoom(g,h.id),'shop');assert(g.command('dispatch',{questId:'rat_nest',heroIds:[h.id]}).ok);const run=g.state.runs.at(-1);assert.equal(M.activity(g,h).phase,'travelling');assert.equal(M.followRoom(g,h.id),'adventurers');g.state.simTime=run.battleAt;assert.equal(M.activity(g,h).phase,'fighting');g.state.simTime=run.battleEndAt;assert.equal(M.activity(g,h).phase,'returning');run.result.victory=false;g.state.simTime=run.returnAt;g._return(run);assert.equal(M.activity(g,h).phase,'recovering');assert.equal(M.followRoom(g,h.id),'adventurers');g.tick(h.recoverUntil-g.state.simTime);assert.equal(M.followRoom(g,h.id),'shop');assert.equal(M.followRoom(g,'missing'),null);});
test('viewing room progression and hero activity does not mutate the save',()=>{const g=make(),before=g.exportSave();for(const room of ['smith','mine','forge','shop','adventurers']){M.progress(g,room);M.stage(g,room);M.artKey(g,room);M.roomName(g,room);M.requirement(room);}for(const h of g.state.adventurers)M.activity(g,h);assert.equal(g.exportSave(),before);});
