/* Design-book interaction only. Does not import the game, read saves or create assets. */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const escape = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stages = ['Humble', 'Established', 'Inherited', 'Guildhouse', 'Celestial'];
  const station = (name, type, u, v, purpose, action, animation, blocker) => ({name,type,u,v,purpose,action,animation,blocker});
  const rooms = [
    {id:'smith', label:'Smith', title:'The maker’s study', deck:'A personal room where skill, not wealth, is the centrepiece.', tone:'#889579', floor:'#8a7257', people:[[.6,.68,'founder']],
      stations:[
        station('Maker’s desk','desk',.2,.18,'A worn desk holds the founder’s ledger, wax seal and current working plan.','Open name, calling, attributes and exact derived bonuses. Unspent points remain visible without a separate “Improve smith” button.','An idle founder studies a pattern and makes notes. If working elsewhere, the desk stays empty.','An unspent-point indicator is a quiet UI badge; no forced modal interrupts the queue.'),
        station('Mastery cabinet','shelf',.76,.15,'A cabinet holds representative pieces for learned item classes, with stamped level medallions.','Choose a class to see the large mastery level, XP bar, bonuses and next relevant unlock.','A selected sample rotates slowly only while inspected. Newly earned mastery gets one brief glint.','Locked classes are concealed. Next-pattern guidance follows the existing first/second variant path, not the demanding prestige branch.'),
        station('House furnishings','bench',.24,.77,'A chair, rug and display stand make permanent furnishings tangible.','Inspect owned furnishing levels, next cost and cumulative effect. Keep these below personal development in the panel.','Cloth edges settle; a small lamp warms the seat. Objects change only with purchased levels.','Every unaffordable level lists the missing gold; owned furniture remains present across careers.'),
        station('House chronicle','book',.76,.73,'A closed family book becomes an illustrated record of significant crafts and victories.','Read earned achievements and house history. Legacy links appear only after eligibility.','A page turn reveals the selected record. No unearned crown or late-game heirloom is displayed.','Before Legacy, this is a history book, not a greyed-out spoiler of all future talents.')
      ],
      looks:['A patched roof, small drafting desk, one wall shelf and a faded woven runner. Warm afternoon light falls through a repaired window.','A fitted desk, matching tool cabinet and a clean wool rug. The room is still recognisably the small original workshop.','An inherited writing alcove, stored patterns and the first family portrait. Owned furnishings survive as familiar anchors.','A craftsman’s library with sliding ladder, framed champion seals and carefully lit study tables.','A miniature observatory-library: brass star mechanisms, deep blue glass and inherited masterworks. Fine detail, not a brighter screen.'],
      briefs:[['Composition & light','Quiet, vertical shelving frames the desk; the readable central object is the open ledger. Pale green daylight and a small amber lamp make this room calm after the Forge.'],['Relevant interface','Name, calling, four attributes, unspent points, compact bonus breakdown and smith XP. Mastery levels are larger than their labels. Furnishings sit below development; employees have their own room.'],['Sound & ambience','Paper, a soft chair creak and a restrained plucked theme. Page sounds happen on an actual selection, not on a perpetual loop.'],['Asset checklist','Cutaway study shell, desk and stool, seven calling desk details, modular mastery cabinet, books, rug, lamp and furnishing-level attachments.']],
      intro:'Your skills shape every piece. Allocate your points, choose a class to practise, then begin work in the Forge.'
    },
    {id:'mine', label:'Mine', title:'The lantern workings', deck:'A cut section of the hillside, with visible seams and busy little hauling routes.',tone:'#686f61',floor:'#827660',people:[[.2,.48,'miner'],[.66,.49,'miner']],
      stations:[
        station('Open seams','vein',.22,.1,'Coal, copper and tin outcrops lie in rough rock. Each unlocked seam has its own colour, fracture shape and crew posts.','Select a seam to assign workers; show assigned headcount, load time, yield and destination bin. Coal is first in the textual list.','Crews swing picks, sort stone and carry a load to the route marker. Visual cycles repeat within the actual slow extraction timer.','Full assigned bins redirect a crew to another available seam. The panel names both assignment and temporary work, with a “Full bin” explanation.'),
        station('Next working','gate',.76,.1,'One shored tunnel ends at a closed timber gate; deeper seams stay concealed.','Inspect the next ore licence, cost and all missing proofs. Iron licence is the first main ore unlock; it still requires its actual champion proof.','Dust drops near a sealed wall; no miner works through a locked gate. The gate opens when the licence is owned.','Main depth progression and optional Surveyor’s ledger are visibly separate. Buying exploration does not unlock Iron.'),
        station('Cart & bins','cart',.72,.55,'A short rail carries ore into separate lidded bins, with a scale beside it.','Help a cart, inspect exact capacities and view what each crew is producing.','Load height roughly follows fill. A manually completed cart can spill a small visual excess when the rules lose overflow.','No invisible overflow bank. Show the actual lost amount; the view does not convert decorative rubble into resources.'),
        station('Survey table','desk',.2,.74,'A folded shaft map holds depth, workforce and storage plans.','Develop room opens Depth / Workers / Storage; Open workings contains material buy and sell controls.','New owned supports, hoists and storage sections are fitted on the next room visit.','Show cost and earned-access requirements on each node. The available optional branch is labelled “Exploration”.'),
        station('Supply shelter','supplies',.75,.85,'Wood lengths, leather rolls and oil bottles are kept dry at the entrance.','A compact right-side supply panel shows amounts and buy controls together.','The prop changes approximate fullness only; purchases update exact quantities immediately.','The same purchase validation as the Forge applies. No extra market screen or bars for purchased supplies.')
      ],
      looks:['Packed earth, rough-cut rock, two lanterns, hand carts and patched timber supports. No tiled floors or decorative palace columns.','Better bracing and a short rail spur; clearly separated coal and ore bins, a small sorting shelter and drainage channel.','An inherited shaft with a worked hoist, timber mezzanine and measured ore sorting. The hillside remains visibly geological.','An engineered underground gallery with lifts, ventilation and mineral specimens around a proper survey office.','A deep starstone cavern crossed by careful brass walkways and suspended crystal instruments. Machinery is exceptional; the mountain still dominates.'],
      briefs:[['Composition & light','Seams occupy the back rock face. Hauling routes cross the middle, bins sit near the front. Warm lantern pools contrast with a cool slit of daylight at the entrance.'],['Relevant interface','Seam assignment, actual current work, exact bin amounts/capacity, time to next load and the next licence blocker. Small supply panel at right; no large empty scene header.'],['Workers & audio','Ada inspects supports; Oswin checks bins and loads. Hired crews work separately. Distant pick taps and wheel rumbles are staggered, with occasional silence.'],['Asset checklist','Layered rock shell, six geological seam kits, coal pile, rough floor, bracing, rail/cart, modular bins, hoist, survey desk and visible hired crew markers.']],
      intro:'Assign a crew to the material your next batch needs. Workers keep hauling while you are away; full bins and locked seams explain where progress stops.'
    },
    {id:'smelter',label:'Smelter',title:'The casting yard',deck:'Ore becomes useful metal in a small, open-sided foundry.',tone:'#a47757',floor:'#a39070',people:[[.46,.32,'tender'],[.73,.76,'assayer']],
      stations:[
        station('Crucible furnace','furnace',.25,.17,'A rounded refractory furnace holds the active metal charge. Bellows, tongs and a safe working circle give it scale.','Choose available alloy, grade, batch count and ingot target. Show exact inputs reserved and total output.','Ivo tends the heat; the metal level and colour follow the current batch stage. Work is not completed by the pour animation.','If fuel or ore is missing, the queued job names the shortage. At full output capacity, the next batch stays unstarted and its fuel stays unspent.'),
        station('Casting bench','casting',.68,.34,'A stone bench holds moulds, a pouring channel and cooling bars.','Inspect the active batch, expected ingot properties and remaining work time.','A brief ladle pour, settling metal and a cooling gradient correspond to the saved progress. One animation can represent a larger batch.','No perpetual pouring when paused. A last batch may exceed the remaining space; label its actual overflow.'),
        station('Ingot rack','shelf',.75,.77,'Bins organise finished ingots by material and grade. Grade stamps remain distinguishable without colour.','Inspect counts and capacities. Stock targets use the same materials the Forge will consume.','Bars appear or leave as counts change. A full rack visibly has no open slots.','Capacity includes other furnaces’ committed output. Parallel furnaces cannot all start against the same remaining space.'),
        station('Assay station','desk',.18,.77,'Elsbet’s small balance and cut sample show that metallurgy changes what the item can do.','Develop Alloys / Quality / Speed; compare standard, tough and spring grades with benefits and tradeoffs.','Elsbet tests a sample while on duty and rests in the common room when off.','Unknown alloys remain concealed. The next crucible shows its earned licence and gold requirement.')
      ],
      looks:['A single patched clay furnace, hand bellows, reused stone mould table and short iron rack in a soot-dark shelter.','A sound chimney, permanent casting bed and organised ingot bins. More orderly rather than fantastically ornate.','Inherited crucibles and a dedicated assay alcove, with wheeled mould trays and a larger extraction hood.','A compact industrial foundry: linked bellows, multiple owned crucibles and refined insulated channels.','A celestial induction chamber around a starforged crucible, with dark ceramic shielding and controlled luminous metal.'],
      briefs:[['Composition & light','The furnace mouth is the warm focal point. Cooling racks stay in soft neutral light so material differences remain legible. Stone channels, never a wooden pouring surface.'],['Relevant interface','Inputs → output, grade tradeoff, active batch, queued batches and target stock. When full, “Waiting for ingot space” replaces a misleading running timer.'],['Workers & audio','Ivo tends; Elsbet assays. Furnace roar remains low and continuous; pours and tongs sound only when relevant. Character rest never shuts down already authorised base production.'],['Asset checklist','Crucible stages, bellows, chimney, refractory bricks, mould sizes, animated ladle, ingot/grade set, racks, scales and material sample trays.']],
      intro:'Turn ore into the ingots your next recipe requires. Set a safe target; a completely full rack will wait before starting another batch.'
    },
    {id:'forge',label:'Forge',title:'The heart of the house',deck:'A close, tactile view of the item being made, surrounded by the tools that make it possible.',tone:'#946e50',floor:'#967a58',people:[[.48,.5,'founder'],[.18,.65,'apprentice']],
      stations:[
        station('Hearth & anvil','hearth',.24,.17,'A masonry fire and anvil form the room’s strong silhouette; the smith’s working route stays unobstructed.','Choose Team / Contract / Shop stock / Practice intent, then recipe type, material, treatment and enchantment.','The smith heats a blank, walks to the anvil and shapes it. Footsteps stop before a hammer stroke.','Only unlocked machines are present. A blocked job names the input or requirement, while the smith safely tidies the area.'),
        station('Active workpiece','anvil',.55,.49,'The selected work sits at a clear central scale, with a dedicated close-inspection view.','Inspect shape and known properties, add eligible finishing, review remaining time or cancel with the exact saved refund.','Blank → shape → assembly → finish. Rotate the preview without rotating the whole room.','Queued items show a plan, not a magically finished object. A random prefix is not revealed before it exists.'),
        station('Specialist benches','bench',.78,.13,'Grinding, tempering, cloth, leather and rune stations form an expandable back corner.','Inspect owned machinery and develop Recipes / Quality / Speed. Select only the next appropriate pattern path.','Tomas assembles and grinds; Sybill inscribes. Garments are cut and stitched; bows are shaped and strung.','A worker never uses a machine that has not been unlocked. Later corners are ordinary wall space until earned.'),
        station('Finished work trolley','cart',.73,.83,'A small trolley receives completed commissions, with visible team/contract/sale destination tags.','See the next queued jobs, their material cost, destination and finishing passes. Craft 1 / 5 / Max stays in the bottom task panel.','A finished item briefly rests here before its authoritative route places it in the armoury, dispatch or display.','Warehouse capacity and invalid team upgrades produce a clear held state. A delivery animation never changes ownership twice.'),
        station('Supplies & patterns','supplies',.16,.82,'Compact wood, leather and oil storage sits near a rolled-pattern rack.','Purchased supplies are grouped at right. Recipe filters stay grouped as Weapons / Armour / Other, always within an item type.','Low supplies change stack heights. Idle smith sweeps filings without progressing a paid job.','The next pattern shows exact missing stats, mastery, recipe or access. Prestige variants do not obscure the next tier’s normal path.')
      ],
      looks:['A repaired brick firebox, a small anvil on a thick stump, one tool rail and a rough assembly bench. Plenty of visible room to grow.','A substantial hearth, owned grinding wheel and a proper workbench. Better lighting reveals the first precise, well-finished pieces.','An inherited workshop with tempering trough, specialist alcoves and labelled pattern drawers.','A guild forge with overhead mechanical assistance, exact fitting benches and a quiet rune room.','A magnificent but functional star forge: dark stone, articulated brass tooling and controlled pools of celestial heat. The item remains the brightest point.'],
      briefs:[['Composition & light','Hearth to rear left, active work in the centre, specialist benches behind. Warm firelight meets a large cool window. The item inspector has a neutral-light toggle for judging materials.'],['Relevant interface','Intent → type/recipe → material/grade → treatment/enchant → quantity. Active craft and queue remain visible. Quality is a number plus expected finishing gains, not a vague coloured adjective.'],['Craft pacing','Existing durations and diminishing finishing are retained. Short gestures repeat during long jobs; machinery speed reflects actual progress without requiring one swing per simulated work unit.'],['Asset checklist','Five construction stages per family where applicable; anvil/hearth, grinding wheel, temper trough, stitching bench, rune table, clamp mounts, wood racks and fitted tool sockets.']],
      intro:'Choose who the piece is for, then choose the work. Watch its construction and use finishing when extra quality is worth the extra time.'
    },
    {id:'shop',label:'Shop & armoury',title:'The window on the town',deck:'A warm storefront with real stock, browsing visitors and a protected place for team equipment.',tone:'#8e9b71',floor:'#9c805a',people:[[.38,.65,'customer'],[.78,.53,'shopkeeper']],
      stations:[
        station('Public displays','shelf',.2,.15,'Slotted wall racks, sword stands, garment forms and a small jewellery case show the actual items offered for sale.','Select an item for stats, material, quality and enchantment; keep Sell and Scrap alongside its details. Empty display slots remain visible.','Visitors follow a short route, pause beside compatible items and inspect a piece. The shelf uses that item’s actual mesh.','Only eligible public stock fills automatically, lowest quality first. Protected team/contract items never fill a gap.'),
        station('Checkout counter','counter',.76,.23,'Perrin’s counter faces the entrance. A receipt tray and parcel shelf make purchases tangible.','Inspect the current visit, compatible interests and sale status. In shop now sits below requests.','A customer sets down the reserved piece, pays and carries it out. A failed purchase produces a polite exit.','Only a short checkout reservation blocks manual sale/scrap; label it. If a viewed item sells, show its sale notice there, not after every ordinary sale.'),
        station('Team armoury','armour',.78,.77,'A screened fitting corner holds three named gear stands and protected storage.','Choose a fighter and slot; show only improving stock, with green gains and red tradeoffs. Inspect equipped pieces on their 3D body.','A fitting pose changes actual meshes. Daggers fit either compatible hand; two-handed weapons clear incompatible off-hand gear.','Busy fighters keep their launch gear. Completed team work equips after the match when valid; spare pieces stay protected.'),
        station('Contract dispatch','desk',.19,.77,'Clara’s order ledger and wrapped parcels sit apart from retail stock.','Show at most five lowest-level feasible requests, current fulfilment and exact rewards. Place a compact warehouse list below the displays.','Qualifying pieces are packed; a courier can collect a visual parcel after automatic completion.','Only requests the smith can make appear. Warehouse fulfilment is automatic, regardless of whether the courier animation is loaded.')
      ],
      looks:['A tiny stall-room, one curtain, two mismatched display racks and a modest plank counter. Broad window light makes even basic wares attractive.','A repaired shopfront, fitted cases, visible empty slots and a private team fitting corner.','An inherited showroom with alcove windows, a practical stock lift and established contract desk.','A respected guild boutique with individual stands, fine joinery and illuminated craftsmanship samples.','An extraordinary gallery of commissioned objects, with glasslike warded cases and a discreet celestial crest. Stock still determines what is actually on display.'],
      briefs:[['Composition & light','The entrance is visible at front left; shelves wrap the back, checkout occupies right. A clear central browsing loop prevents intersections with staff routes.'],['Relevant interface','Display sockets first, five feasible requests, current visitors, then compact warehouse. Team armoury is an inspector mode; no detached warehouse/craft shortcut buttons or recent-sales block.'],['Service & audio','Perrin sells; Clara dispatches. Footsteps, soft cloth and one checkout chime convey trade. Cosmetic chatter has no subtitles required for essential information.'],['Asset checklist','Weapon/garment/jewellery displays with item sockets, empty cases, fitting mannequin/body stands, door, counter, packages, visitor carry poses and checkout area.']],
      intro:'Your shelves fill themselves with sale stock. Team commissions stay protected; contracts deliver from the warehouse as soon as their requirements are met.'
    },
    {id:'arena',label:'Arena',title:'The proving ring',deck:'A miniature sporting ground where the shape and weight of the team’s equipment matter visually.',tone:'#a79670',floor:'#c2ab79',people:[],
      stations:[
        station('Home preparation','armour',.13,.76,'A cloth awning holds the home team’s three preparation positions.','Inspect final stats, XP, exact equipped gear and class eligibility. Set active roster, front/back lines and doctrine.','Heroes check straps and stretch with their real equipment. No generic weapon replaces an equipped item.','A full health/eligibility summary explains a blocked launch. No random nameless team replaces the fixed roster.'),
        station('Fighting ground','arena',.48,.45,'Sand, boundary stones and low rails leave a clean view of both battle lines.','Gather & launch begins one real-time match. During it, follow a fighter or return to overview.','Approach, wind-up, contact, block, projectile flight, recovery and yielding follow the actual combat state.','A stable timeout and path recovery prevent endless matches. Switching rooms does not pause the battle or grant a result early.'),
        station('Rival gate','gate',.78,.1,'Distinct shields and pennants mark the chosen rival house.','Inspect tactics, current rung, style wins and the next champion requirement.','Opponents enter through their gate and take their formation before the first attack.','Five scoring wins plus all three styles qualify each rung; the champion still requires all three rungs and a manual launch.'),
        station('Match ledger','book',.8,.83,'The scorer’s table keeps bouts and decisive moments.','Review the last twelve saved fights, inspect the turning point and pin a crafting response.','Replay avatars use historical equipment, not today’s inventory. Playback is clearly labelled REPLAY.','Replays never award gold, qualification or XP. Automatic exhibitions only run when already authorised.')
      ],
      looks:['A sandy practice ring between timber fences, a small awning and a few onlookers. The first champion deserves a scene without a grand stadium.','A repaired local yard with solid rails, clearer gates and several rows of benches.','An inherited training court with carved house crests and a compact covered stand.','A guild amphitheatre with stone seating, hanging pennants and disciplined lighting.','A celestial tournament pavilion with a dark ceremonial roof and luminous heraldry. The sand and fighters remain visually calm.'],
      briefs:[['Composition & light','Higher camera angle than the workshop. Fighters occupy a clear central silhouette zone. Front/back line guides appear in setup or on request, not as permanent neon lanes.'],['Relevant interface','Preparation: name/class, figure, compact stats, gear, qualification. Live: two team health strips, selected fighter and event captions. After: decisive event, outcome, rewards and next requirement.'],['Crowd & sound','Spectators use simple distant rigs or static groups with small pose variation. Crowd swells at a real breach or victory. Contact sounds distinguish metal, wood and cloth without overwhelming room music.'],['Asset checklist','Sand ring, gates, benches, pennants, weapon-appropriate combat clips, projectile prefabs, yield poses, formation markers and versioned historical gear appearance.']],
      intro:'Prepare the team, study the rival and launch. Your fighters act automatically; use what the match reveals to decide what to forge next.'
    },
    {id:'employees',label:'Employees',title:'The common room',deck:'The place where the people who keep the house running become people you recognise.',tone:'#a99a75',floor:'#947b5a',people:[[.38,.6,'resting'],[.68,.77,'resting']],
      stations:[
        station('Department board','board',.2,.15,'Four clearly marked department rows connect staff to Mine, Smelter, Forge and Shop.','See employment, current location, actual contribution, XP and stamina. Follow any hired specialist to their room.','Small assignment markers move on the board; the physical person stays in one room.','Unhired staff are candidates on cards, not workers secretly contributing. Crew headcount is distinct from named specialists.'),
        station('Long table','table',.48,.56,'A heavy communal table has mismatched mugs, bread, a kettle and enough seating for off-duty staff.','Give manual time off or return an employee to duty; show recovery rate and ready estimate.','Resting employees sit, eat, converse or stretch. A character at zero stamina is visibly resting, not still swinging a hammer.','Managed shifts use the existing 35/90 thresholds. Manual leave does not silently end at full stamina.'),
        station('Training corner','bench',.77,.17,'Small practice tools and a slate illustrate earned expertise.','Open Training / Welfare / Organization upgrades. Explain cost, access proof and effective department bonus.','Off-duty practice is cosmetic unless an actual training rule grants XP. New rank details appear in clothing and equipment care.','No new passive XP is invented just because an actor rehearses a motion.'),
        station('Quiet alcove','bed',.18,.81,'A comfortable bench bed and curtained nook give tired workers an obvious destination.','Inspect stamina bands and the contribution lost while tired. Furnishings remain managed in the Smith section.','A staff member enters the nook, removes heavy gloves and rests. The same identity returns to work later.','Rest continues offline and in unloaded rooms. A missing animation can never strand someone off duty.')
      ],
      looks:['A small common room with a table, kettle, coat pegs and a bench bed. The comfort comes from people and warm light.','A sound kitchen corner, padded benches and an orderly department board.','An inherited refectory with a quiet reading niche, better bedding and personal lockers.','A guild hall with a training annex, well-kept tools and room for experienced staff to teach.','A magnificent but intimate house commons: a garden conservatory, crafted furniture and staff-made keepsakes. No anonymous luxury hotel.'],
      briefs:[['Composition & light','The table sits centrally, with department board at rear and resting nook visible to one side. Warm low lights contrast with the Mine’s directional lanterns.'],['Relevant interface','Four department filters, stable employee cards, large enough XP/stamina bars, current location, effective bonus and leave/return action. Upgrades stay prominent.'],['Character identity','Eight existing names receive distinct hair, silhouette, apron and work props. Level progression adds restrained patches or badges; stamina is communicated by pose and text, not only colour.'],['Asset checklist','Table and seating sockets, mugs, kettle, bench bed, personal lockers, assignment board, coats, resting clips and department-specific outfits.']],
      intro:'Hire at the bottleneck, let employees learn through work, and give them time to recover. Follow a specialist to see their contribution in the house.'
    },
    {id:'legacy',label:'Legacy',title:'The hall of names',deck:'One extraordinary room, revealed only after the house has earned a history worth inheriting.',tone:'#7c8e8b',floor:'#86927f',people:[[.53,.73,'founder']],
      stations:[
        station('Family monument','monument',.47,.17,'A carved anvil rests beneath an enormous brass-and-glass orrery. Names and earned seals are its ornament.','Read the generation, earned legacy currency and the exact retirement preview.','Soft constellations turn slowly above the monument. The founder stands still rather than performing endless ceremony.','Keep the room concealed until the existing fifth-champion and credited-time requirements are met. No early navigation teaser.'),
        station('Inheritance archive','shelf',.84,.47,'An archive holds workforce, patron and pattern charters as physical volumes.','Choose permanent talents and review the next career’s changed opening with exact effects.','Purchased research opens a book, lights an index or adds a model of the unlocked method.','Costs and dependencies come from the actual talent data. The model cannot imply a purchased capability before it is earned.'),
        station('Heirloom case','case',.2,.75,'A single carefully lit case holds the chosen inherited item.','Inspect eligible stored equipment and select the one piece to carry through retirement.','The actual item rotates only in its close inspection view. Its old maker’s stamp remains.','The selection must still exist and be eligible at confirmation; displayed placeholders cannot be inherited.'),
        station('Chronicle & trials','book',.77,.83,'Small league seals, research records and Crucible markers tell the house’s history.','Read discoveries, trial progress and persistent studies; review the saved retirement summary.','Each earned milestone adds one restrained object or light. No wall of flashing reward icons.','Retirement is explicit and confirmed after a full keep/reset preview. A reset run remains a different menu action with no spark reward.')
      ],
      looks:['A single lavish hall: dark carved wood, pale stone, old brass and a suspended night-sky glass canopy. Precious empty space gives the first heirloom importance.'],
      briefs:[['Composition & light','Strong vertical monument at the back; the chosen heirloom catches one warm shaft of light. Cool celestial fill stays dim enough for details and labels to read.'],['Relevant interface','Generation, eligible reward, next-career charter, talent branches, heirloom selection and what persists. Confirmation names losses and retained progress in plain language.'],['Long-term growth','Keep the architecture fixed. Research and generations populate sockets with books, seals and miniature inventions; ownership lights the orrery’s segments.'],['Asset checklist','One hall shell, monument, orrery, display case, archive, seal mounts and earned-content attachment sockets. Reuse the actual heirloom item mesh.']],
      intro:'Your house has earned an inheritance. Review what survives, choose how the next generation begins, and retire only when you are ready.'
    }
  ];

  const families = [
    ['Daggers','Bollock knife, rondel and long quillon profiles; real left/right hand attachment.'],['Swords','Arming blade, distinct guard/pommel kits, properly scaled grip and fuller.'],['Axes','Hand axe, broad cutting head and long-haft construction; separate eye and haft.'],['Maces','Round, flanged and specialised heads; clear mass and socketed shafts.'],['Polearms','Spear, glaive and halberd-like heads; langets, shaft wraps and two-handed reach.'],['Bows','Simple stave, recurved or reinforced limbs; string and brace point fit the rig.'],['Arcane foci','Crozier and staff forms, enclosed stones, readable grip zones and spell sockets.'],['Cloth armour','Tunic and vestment panels, layered hems, woven surface and tailored seams.'],['Leather armour','Jerkin and reinforced panel silhouettes, lacing, straps and shaped shoulders.'],['Mail armour','Hauberk shape, coif-like collar detail where part of the garment, baked linked texture.'],['Shields','Round, heater and pavise construction; boss, rim, rear straps and wooden core.'],['Other offhands','Lantern, book or ward-object families as their actual recipes specify.'],['Tools','Hammer, tongs and fine instruments; belt attachment as well as inspection view.'],['Charms','Pendant, reliquary and cord-mounted tokens; placed visibly at the neck or belt.'],['Rings','Band, signet and raised setting; hand socket plus enlarged inspection.'],['Instruments','Small stringed/body kits, bridge, pegs and strap; correct equipped slot from data.'],['Talismans','Ampulla and seal-like cases with cord/chain; mounts follow the recipe’s slot.']
  ];
  const staff = [
    ['Ada','Pit foreman','Mine','Stocky silhouette, short tied hair, rolled shaft map. Inspects braces and redirects hauling.','#ad8555'],['Oswin','Quartermaster','Mine','Long canvas apron, ledger at belt, broad gloves. Checks material bins and load weights.','#7e9278'],['Ivo','Furnace tender','Smelter','Thick leather sleeves, cap and long tongs. Tends the crucible from its safe edge.','#b87245'],['Elsbet','Assayer','Smelter','Neat waistcoat, braid, magnifier and scales. Checks a small metal sample.','#9b9182'],['Tomas','Apprentice','Forge','Short apron, tousled hair, rolled cuffs. Grinds, assembles and clears the bench.','#8c9b83'],['Sybill','Runekeeper','Forge','Dark indigo cuffs, tied-back hair, fine stylus. Engraves deliberate, careful strokes.','#8c84a8'],['Perrin','Shopkeeper','Shop','Warm waistcoat, keys and folded cloth. Opens cases, polishes and handles checkout.','#ab895a'],['Clara','Envoy','Shop','Travel cape, order folio and ribbon spool. Prepares contract parcels at dispatch.','#749897']
  ];

  // Oblique diagrams are intentionally simple spatial plans, not placeholder game assets.
  const iso = (u,v,z=0) => [380+(u-v)*285,145+(u+v)*120-z];
  const points = (coords) => coords.map(p=>p.join(',')).join(' ');
  const poly = (coords,fill,stroke='#152c2580') => `<polygon points="${points(coords)}" fill="${fill}" stroke="${stroke}" stroke-width="1.4"/>`;
  function box(u,v,w,d,h,c){
    const a=iso(u,v),b=iso(u+w,v),e=iso(u+w,v+d),f=iso(u,v+d),up=p=>[p[0],p[1]-h];
    return poly([a,b,up(b),up(a)],c[1]||c[0])+poly([b,e,up(e),up(b)],c[1]||c[0])+poly([e,f,up(f),up(e)],c[2]||c[0])+poly([up(a),up(b),up(e),up(f)],c[0]);
  }
  function person(x,y,color='#ce9e61',scale=1){
    return `<g class="scene-person" transform="translate(${x} ${y}) scale(${scale})"><ellipse cy="2" rx="13" ry="5" fill="#10291f55"/><path d="M-6 -18L-7 0M6 -18L7 0" stroke="#3c493d" stroke-width="6" stroke-linecap="round"/><path d="M-8 -37Q0 -42 8 -37L11 -18Q0 -12 -11 -18Z" fill="${color}" stroke="#2c4133"/><path d="M-8 -34L-14 -21M8 -34L14 -24" stroke="${color}" stroke-width="6" stroke-linecap="round"/><circle cy="-48" r="9" fill="#dcb892"/><path d="M-9 -49Q-10 -64 8 -53L8 -48Q0 -53 -9 -49" fill="#635143"/><path d="M-6 -1L-11 1M6 -1L11 1" stroke="#293b32" stroke-width="5" stroke-linecap="round"/></g>`;
  }
  function prop(s,index,stage){
    const {u,v,type}=s,[x,y]=iso(u,v),wood=['#b58b57','#70573c','#856542'],stone=['#c0b49a','#777763','#92917a'];
    let shape='';
    if(['desk','table','bench','casting','counter'].includes(type)){
      shape=box(u-.13,v-.07,.28,.16,35,type==='casting'?stone:wood);
      shape+=`<path d="M${x-13} ${y-42}l18 -8 18 8 -18 8Z" fill="${type==='casting'?'#d88c46':'#e6d7ae'}" stroke="#715d41"/>`;
      if(type==='bench')shape+=`<circle cx="${x+28}" cy="${y-30}" r="14" fill="#888f7b" stroke="#c4c4a5" stroke-width="4"/>`;
    }else if(['hearth','furnace'].includes(type)){
      shape=box(u-.11,v-.1,.25,.22,67,['#b09d82','#726953','#8c7a60']);
      shape+=`<path d="M${x-27} ${y-7}v-29q12 -20 27 -6v30Z" fill="#332c24"/><path d="M${x-21} ${y-10}q-5 -12 8 -24q-2 14 8 9l-2 17Z" fill="#edb05b"/><path d="M${x-10} ${y-9}l-2 -15 7 7Z" fill="#fff0b0"/>`;
      shape+=box(u-.02,v-.06,.11,.12,112,['#9e967f','#5e6656','#79806a']);
      shape+=`<path d="M${x+2} ${y-117}q-16 -17 0 -30q14 -14 2 -29" stroke="#b9c1a0" stroke-width="8" opacity=".18" fill="none"/>`;
    }else if(type==='anvil'){
      shape=box(u-.055,v-.055,.11,.11,27,wood);
      shape+=`<path d="M${x-31} ${y-44}h48l19 6 -23 4 -7 13h-25l5 -12Z" fill="#82978e" stroke="#243e37" stroke-width="2"/><path d="M${x-17} ${y-44}h28" stroke="#d5e0c7" stroke-width="3"/>`;
    }else if(['shelf','armour','case'].includes(type)){
      shape=box(u-.15,v-.05,.31,.09,type==='case'?49:83,['#aa9169','#534f37','#78674b']);
      const ys=type==='case'?[y-29]:[y-18,y-44,y-69];
      for(const [i,yy] of ys.entries()){
        shape+=`<path d="M${x-40} ${yy}l58 25 19 -8" fill="none" stroke="#d5bd83" stroke-width="4"/>`;
        if(stage>0||i===0)shape+=`<path d="M${x-25} ${yy-12}l3 -20 4 21m12 5l3 -27 4 29m9 2l3 -23 4 25" fill="none" stroke="#aebcac" stroke-width="4"/>`;
      }
    }else if(type==='vein'){
      for(let i=0;i<4;i++){const dx=(i-1.5)*24,dy=Math.abs(i-1.5)*7;shape+=`<path d="M${x+dx-20} ${y+dy}l-4 -34 20 -30 24 19 8 35 -23 19Z" fill="${['#475044','#866953','#83908a','#676d5b'][i]}" stroke="#b2b69a66"/><path d="M${x+dx} ${y+dy-31}l8 -10 8 14 -9 7Z" fill="${i===0?'#272f2a':i===1?'#c18b60':'#b8bbaa'}"/>`;}
    }else if(type==='gate'){
      shape=box(u-.14,v-.03,.035,.08,99,wood)+box(u+.12,v-.03,.035,.08,99,wood)+box(u-.14,v-.03,.295,.08,105,wood);
      shape+=`<path d="M${x-30} ${y-20}l46 -26M${x-29} ${y-47}l46 24" stroke="#b49d71" stroke-width="7"/><circle cx="${x-5}" cy="${y-36}" r="8" fill="#c4a45c"/>`;
    }else if(type==='cart'){
      shape=box(u-.08,v-.08,.19,.18,27,wood);
      shape+=`<circle cx="${x-29}" cy="${y+10}" r="9" fill="#354b3a" stroke="#ad996e" stroke-width="3"/><circle cx="${x+25}" cy="${y+13}" r="9" fill="#354b3a" stroke="#ad996e" stroke-width="3"/><path d="M${x-24} ${y-26}l20 -15 25 16" fill="#87917a"/>`;
    }else if(type==='supplies'){
      shape=box(u-.07,v-.1,.15,.12,32,wood)+box(u+.05,v+.04,.13,.12,20,['#9b8663','#706348','#857050']);
      shape+=`<path d="M${x-25} ${y-17}l-13 -24 9 -4 15 24" fill="#b4a176"/><path d="M${x+25} ${y-22}v-14h-7v14q-8 7 0 16h7q7 -7 0 -16" fill="#a3b67d" stroke="#314936"/>`;
    }else if(['book','board'].includes(type)){
      shape=box(u-.12,v-.05,.25,.09,type==='board'?80:35,wood);
      shape+=`<path d="M${x-33} ${y-42}l28 -13 32 15 -30 14Z" fill="#e1cd9d" stroke="#594d38"/><path d="M${x-5} ${y-55}l2 27" stroke="#8e754e"/>`;
    }else if(type==='bed'){
      shape=box(u-.16,v-.09,.34,.18,18,wood)+box(u-.14,v-.075,.29,.15,26,['#c3b893','#777b61','#a19a78']);
      shape+=`<path d="M${x-38} ${y-25}l15 -7 20 9 -15 6Z" fill="#e3d8b9"/>`;
    }else if(type==='arena'){
      shape=`<ellipse cx="${x}" cy="${y}" rx="115" ry="53" fill="#c7b686" stroke="#dfcd9d" stroke-width="8"/><ellipse cx="${x}" cy="${y}" rx="92" ry="40" fill="none" stroke="#9a916b" stroke-dasharray="5 7"/>`;
      shape+=person(x-34,y+8,'#a9be99',.9)+person(x+40,y+12,'#c28b69',.9);
    }else if(type==='monument'){
      shape=box(u-.08,v-.08,.18,.18,61,stone);
      shape+=`<ellipse cx="${x}" cy="${y-115}" rx="45" ry="19" fill="none" stroke="#c9b06b" stroke-width="4"/><ellipse cx="${x}" cy="${y-115}" rx="21" ry="47" fill="none" stroke="#c9b06b" stroke-width="3" transform="rotate(35 ${x} ${y-115})"/><circle cx="${x}" cy="${y-115}" r="9" fill="#d2ded1"/><path d="M${x} ${y-70}v-32" stroke="#b8a168" stroke-width="4"/>`;
    }
    return `<g class="scene-object ${index===selectedStation?'selected':''}" role="button" tabindex="0" aria-label="Inspect ${escape(s.name)}" data-station="${index}"><ellipse class="select-ring" cx="${x}" cy="${y+8}" rx="55" ry="22"/>${shape}<circle cx="${x+42}" cy="${y+25}" r="12" fill="#ddcd9e" stroke="#263e31" stroke-width="2"/><text x="${x+42}" y="${y+29}" text-anchor="middle" font-size="11" fill="#294236" font-family="Segoe UI,sans-serif">${index+1}</text></g>`;
  }
  let selectedRoom=3, selectedStage=0, selectedStation=1;
  function scene(room,stage,cover=false){
    const a=iso(0,0),b=iso(1,0),c=iso(1,1),d=iso(0,1),lift=p=>[p[0],p[1]-118];
    let svg=`<svg viewBox="0 0 760 435" role="img" aria-label="${escape(room.label)} spatial layout study"><ellipse cx="380" cy="363" rx="246" ry="47" fill="#122c2355"/>`;
    svg+=poly([b,c,d,[d[0],d[1]+20],[c[0],c[1]+20],[b[0],b[1]+20]],'#263f32');
    svg+=poly([a,b,c,d],room.floor)+poly([a,b,lift(b),lift(a)],room.tone)+poly([d,a,lift(a),lift(d)],'#61725a');
    // Large floor seams are compositional guides, absent in the mine's rough earth.
    if(room.id!=='mine')for(let i=1;i<8;i++)svg+=`<path d="M${iso(i/8,0).join(' ')}L${iso(i/8,1).join(' ')}" stroke="#35483533"/>`;
    if(room.id==='mine')for(let i=0;i<11;i++){let x=150+i*39,y=270+(i%3)*20;svg+=`<path d="M${x} ${y}l12 -5 8 6 -13 5Z" fill="#53624c55"/>`;}
    svg+=`<path d="M${iso(.13,.85).join(' ')}L${iso(.46,.64).join(' ')}L${iso(.6,.29).join(' ')}" fill="none" stroke="#e3d3a966" stroke-width="2" stroke-dasharray="5 7"/>`;
    if(stage>0)svg+=box(.04,.94,.12,.045,34,['#b8a06c','#726442','#8d7d56'])+box(.87,.08,.05,.1,106,['#b8a06c','#726442','#8d7d56']);
    if(stage>1)svg+=`<path d="M135 112L146 68 159 122Z" fill="#9fb8a6" stroke="#d2c78e"/><path d="M601 123L615 77 628 135Z" fill="#9fb8a6" stroke="#d2c78e"/>`;
    if(stage>2)svg+=`<path d="M212 54Q379 -40 547 52" stroke="#c9b077" stroke-width="7" fill="none"/>`;
    if(stage>3)svg+=`<path d="M310 35l70 -21 67 27 -63 22Z" fill="none" stroke="#b5d1c6" stroke-width="3"/><circle cx="379" cy="43" r="8" fill="#d3ddbe"/>`;
    svg+=room.stations.map((s,i)=>({s,i})).sort((a,b)=>(a.s.u+a.s.v)-(b.s.u+b.s.v)).map(({s,i})=>prop(s,i,stage)).join('');
    svg+=room.people.map(([u,v,kind])=>{const [x,y]=iso(u,v);return person(x,y,kind==='founder'?'#caa778':kind==='customer'?'#97b29a':'#a2a17b');}).join('');
    svg+=`<text x="380" y="422" text-anchor="middle" class="scene-tiny">${cover?'THE HUMBLE FORGE · COMPOSITION & MATERIAL STUDY':'DASHED LINE = PRIMARY WALKING ROUTE · NUMBERED STATIONS = INSPECTABLE OBJECTS'}</text></svg>`;
    return cover?svg.replace(/role="button" tabindex="0"/g,'aria-hidden="true"').replace(/data-station="\d+"/g,''):svg;
  }
  function renderRoom(){
    const room=rooms[selectedRoom];
    $('room-heading').textContent=room.title; $('room-deck').textContent=room.deck; $('room-counter').textContent=String(selectedRoom+1).padStart(2,'0');
    $('scene-label').textContent=`${room.label.toUpperCase()} / ${room.id==='legacy'?'THE HALL':stages[selectedStage].toUpperCase()}`;
    $('room-sketch').innerHTML=scene(room,selectedStage);
    $('workstations').innerHTML=room.stations.map((s,i)=>`<button data-station="${i}" aria-pressed="${i===selectedStation}">${i+1} · ${escape(s.name)}</button>`).join('');
    const s=room.stations[selectedStation];
    $('station-name').textContent=s.name;$('station-purpose').textContent=s.purpose;$('station-action').textContent=s.action;$('station-animation').textContent=s.animation;$('station-blocker').textContent=s.blocker;
    document.querySelector('.stage-picker').innerHTML=(room.id==='legacy'?['One enduring hall']:stages).map((label,i)=>`<button data-stage="${i}" aria-pressed="${i===selectedStage}">${String(i+1).padStart(2,'0')} · ${label}</button>`).join('');
    $('stage-note').innerHTML=`<b>${room.id==='legacy'?'One architecture; earned exhibits':stages[selectedStage]+' house'}</b>${escape(room.looks[selectedStage])}`;
    $('room-brief').innerHTML=room.briefs.map(([title,body])=>`<article class="card"><h3>${escape(title)}</h3><p>${escape(body)}</p></article>`).join('');
    $('first-visit').innerHTML=`<span class="kicker">First visit</span><p>${escape(room.intro)}</p>`;
    document.querySelectorAll('[data-room]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.room)===selectedRoom)));
  }
  document.querySelector('.room-picker').innerHTML=rooms.map((r,i)=>`<button data-room="${i}" aria-pressed="${i===selectedRoom}">${escape(r.label)}</button>`).join('');
  document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{
    document.querySelectorAll('[data-panel]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));
    document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.panel);
    window.scrollTo({top:0,behavior:'instant'});
  }));
  $('rooms').addEventListener('click',e=>{
    const r=e.target.closest('[data-room]'),s=e.target.closest('[data-station]'),stage=e.target.closest('[data-stage]');
    if(r){selectedRoom=Number(r.dataset.room);selectedStage=0;selectedStation=0;renderRoom();}
    else if(s){selectedStation=Number(s.dataset.station);renderRoom();document.querySelector(`#workstations [data-station="${selectedStation}"]`).focus({preventScroll:true});}
    else if(stage){selectedStage=Number(stage.dataset.stage);renderRoom();document.querySelector(`[data-stage="${selectedStage}"]`).focus({preventScroll:true});}
  });
  $('room-sketch').addEventListener('keydown',e=>{const t=e.target.closest('[data-station]');if(t&&['Enter',' '].includes(e.key)){e.preventDefault();t.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
  $('cover-sketch').innerHTML=scene(rooms[3],0,true);
  $('family-grid').innerHTML=families.map(([name,copy])=>`<article><h4>${name}</h4><p>${copy}</p></article>`).join('');
  $('staff-grid').innerHTML=staff.map(([name,role,dept,desc,color])=>`<article><svg class="mini-portrait" viewBox="0 0 50 60" aria-hidden="true">${person(25,58,color)}</svg><span class="kicker">${dept}</span><h3>${name}</h3><small>${role}</small><p>${desc}</p></article>`).join('');
  $('room-print-appendix').innerHTML=rooms.map(r=>`<article style="break-before:page"><h2>${escape(r.title)}</h2><p>${escape(r.deck)}</p>${r.briefs.map(([t,b])=>`<h3>${escape(t)}</h3><p>${escape(b)}</p>`).join('')}<h3>Stations & behaviours</h3>${r.stations.map(s=>`<h4>${escape(s.name)}</h4><p>${escape(s.purpose+' '+s.action+' '+s.animation+' '+s.blocker)}</p>`).join('')}<h3>Room evolution</h3>${r.looks.map((l,i)=>`<p><b>${r.id==='legacy'?'Enduring hall':stages[i]}:</b> ${escape(l)}</p>`).join('')}</article>`).join('');

  function renderItem(){
    const material=$('item-material').value, pattern=$('item-pattern').value, prefix=$('item-prefix').value,enchant=$('item-enchant').value,q=Number($('item-quality').value),shield=enchant==='frost';
    const colors={bronze:['#c39454','#716a47'],iron:['#9ba39b','#4c625c'],steel:['#c7d6cb','#6b8883'],mithril:['#d2ecea','#8ab2bb'],starforged:['#9aacc2','#354952']}[material];
    const glow={none:'#ccd9b5',flame:'#e6a34e',frost:'#a5d8e7',stars:'#bfc7f7'}[enchant];
    const narrow=prefix==='piercing',prestige=pattern==='prestige',train=pattern==='training';
    const blade=narrow?'M244 58L257 200L247 218L239 201Z':train?'M230 100L263 136L261 216L235 216Z':'M247 44L275 183L262 220L232 220L220 183Z';
    let svg=`<svg viewBox="0 0 500 360" role="img" aria-label="Illustration of ${material} ${shield?'shield':'dagger'} with quality ${q}"><defs><linearGradient id="item-metal"><stop offset="0" stop-color="${colors[1]}"/><stop offset=".48" stop-color="${colors[0]}"/><stop offset=".51" stop-color="${colors[1]}"/><stop offset="1" stop-color="${colors[0]}"/></linearGradient></defs><ellipse cx="250" cy="329" rx="86" ry="12" fill="#0e211d99"/><circle cx="250" cy="178" r="138" fill="none" stroke="#c5d5ad22"/><circle cx="250" cy="178" r="145" fill="none" stroke="#c5d5ad0c"/>`;
    if(shield){
      svg+=`<path d="M168 83Q249 50 332 83L325 212Q313 256 250 301Q185 260 175 213Z" fill="#596b58" stroke="${colors[0]}" stroke-width="${q>90?10:6}"/><path d="M190 92V209M220 84V252M250 81V278M280 84V249M309 91V211" stroke="#263f2b55" stroke-width="3"/><circle cx="250" cy="165" r="39" fill="url(#item-metal)" stroke="${colors[0]}" stroke-width="4"/><path d="M250 102V228M212 139L288 190M210 190L289 138" stroke="${glow}" stroke-width="3"/>`;
      if(q>80)svg+=`<path d="M182 91Q250 66 319 91L311 207Q300 246 250 281Q199 242 188 207Z" fill="none" stroke="#c8bc85" stroke-width="2"/>`;
    }else{
      if(enchant!=='none')svg+=`<path d="${blade}" fill="none" stroke="${glow}" stroke-width="22" opacity=".10"/><path d="${blade}" fill="none" stroke="${glow}" stroke-width="12" opacity=".12"/>`;
      svg+=`<path d="${blade}" fill="url(#item-metal)" stroke="${q>70?colors[0]:colors[1]}" stroke-width="2"/><path d="M${narrow?244:247} ${train?125:70}V209" stroke="${prefix==='keen'?'#f7f0c8':colors[0]}" stroke-width="${q>90?2:1}"/><path d="M240 236L237 295Q247 304 259 295L255 235" fill="#806d51" stroke="#243b2d" stroke-width="2"/>`;
      for(let i=0;i<7;i++)svg+=`<path d="M239 ${244+i*7}l17 ${q>70?1:4}" stroke="#b79b6e" stroke-width="2"/>`;
      svg+=train?`<path d="M223 226L272 222V232L226 235Z" fill="${colors[1]}"/>`:`<ellipse cx="247" cy="226" rx="${prestige?47:33}" ry="10" fill="url(#item-metal)" stroke="${colors[0]}" stroke-width="3"/><ellipse cx="247" cy="300" rx="21" ry="7" fill="url(#item-metal)" stroke="${colors[0]}" stroke-width="2"/>`;
      if(q<45)svg+=`<path d="M239 147l14 4m-13 18 16 -3m-9 25 11 2" stroke="#34554c88" stroke-width="2"/>`;
      if(q>110||prestige)svg+=`<path d="M230 224q18 -12 36 0m-28 75 9 -5 10 5" fill="none" stroke="#e5c27f" stroke-width="2"/>`;
      if(q>160)svg+=`<path d="M236 179l11 -18 13 19 -12 22Z" fill="none" stroke="#eed9a3" stroke-width="1.5"/>`;
      if(prefix==='precise')for(let i=0;i<5;i++)svg+=`<path d="M249 ${157+i*9}h8" stroke="#313f32" stroke-width="2"/>`;
      if(enchant!=='none')svg+=`<path d="M247 186l-5 -12 7 -11 -3 -10 6 -11" fill="none" stroke="${glow}" stroke-width="3"/>`;
    }
    if(enchant==='stars')for(const[x,y,s] of [[207,111,6],[295,180,8],[223,244,5]])svg+=`<path d="M${x-s} ${y}h${2*s}M${x} ${y-s}v${2*s}" stroke="${glow}" stroke-width="2"/>`;
    if(enchant==='flame')svg+=`<path d="M288 168q10 -5 6 -14m-84 55q-9 -5 -4 -15" stroke="${glow}" fill="none" stroke-width="2"/>`;
    svg+=`<text x="48" y="330" class="scene-tiny">Q ${q}</text><text x="452" y="330" text-anchor="end" class="scene-tiny">${material.toUpperCase()}</text></svg>`;
    $('item-sketch').innerHTML=svg;$('quality-value').textContent=String(q);
    const m=material[0].toUpperCase()+material.slice(1),pref=prefix==='none'?'':prefix[0].toUpperCase()+prefix.slice(1)+' ';
    $('item-name').textContent=shield?`${m} shield · Frost Ward`:`${pref}${m} ${train?'knife':prestige?'prestige rondel':'rondel'}${enchant==='flame'?' · Flame Etching':enchant==='stars'?' · Falling Stars':''}`;
    $('item-description').innerHTML=`<b>${q<45?'Rough surfaces and irregular wrapping':q<110?'Clean alignment and a measured finish':q<160?'Precise fittings and restrained ornament':'Exceptional finish with inset detailing'}</b><p>${shield?'Armour study: frosted enamel and a clear protective motif. The weapon-only prefix selector is ignored for this shield illustration.':`The ${prefix==='none'?'unmodified':prefix} profile remains identifiable beneath ${enchant==='none'?'unenchanted metal':enchant==='flame'?'a warm, narrow inscription':'a small constellation motif'}.`}</p><small>Exact stats and quality names will come from the shared game data. This study demonstrates visual separation only.</small>`;
  }
  ['item-material','item-pattern','item-prefix','item-enchant','item-quality'].forEach(id=>$(id).addEventListener('input',renderItem));

  const battleStates={
    formation:['Prepare the line','Mara and Renn occupy the home front; Wren takes the rear. Two Iron Choir wardens shield their archer. Equipment is the exact launch snapshot.','Setup markers reveal line assignments. Range does not allow a rear target while an opposing front-line fighter is alive.'],
    engage:['Close to valid range','Melee fighters approach along short lanes. Wren and the rival archer aim at eligible front-line targets. Foot plants and guard poses make contact readable.','Movement and targeting occur in the simulation. The camera follows positions; it does not decide collision or damage.'],
    impact:['A hit has a cause','Renn’s paired blades meet a warden. One contact can be blocked while the full attack budget remains bounded. Wren’s committed arrow resolves at its impact tick.','Block, evasion and critical results come from seeded rules. The effects explain that result; a second dagger does not create a second full-power attack.'],
    break:['The rear is exposed','Both wardens have yielded. The front-line boundary opens and the next valid target is the archer. A brief “Front line broken” caption marks the turning point.','Only now can home attacks select the rear. Already launched projectiles follow their recorded target; no mid-flight bonus retarget.'],
    review:['Find the next craft','The match ledger marks the breach and compares damage before and after it. The team returns to its preparation area; equipment waiting for completion can now be applied.','Rewards settle once by match ID. This storyboard is illustrative; it does not claim a measured win for this loadout.']
  };
  function battle(phase='formation'){
    const p=battleStates[phase],close=['engage','impact'].includes(phase),broken=['break','review'].includes(phase);
    $('battle-title').textContent=p[0];$('battle-copy').textContent=p[1];$('battle-rule').textContent=p[2];
    let svg='<svg viewBox="0 0 760 430" role="img" aria-label="Arena storyboard with two front lines and protected rear fighters"><rect x="35" y="47" width="690" height="316" rx="125" fill="#ab9769" stroke="#d2be8b" stroke-width="10"/><rect x="67" y="77" width="626" height="256" rx="105" fill="#c1b086" stroke="#dfd0a4" stroke-dasharray="6 9"/><text x="135" y="32" text-anchor="middle" class="scene-label">HOUSE TEAM</text><text x="620" y="32" text-anchor="middle" class="scene-label">IRON CHOIR</text><path d="M305 88V325M455 88V325" stroke="#8a855e" stroke-width="2" stroke-dasharray="5 7"/><text x="302" y="350" text-anchor="middle" font-size="10" fill="#394e3a">HOME FRONT</text><text x="458" y="350" text-anchor="middle" font-size="10" fill="#394e3a">RIVAL FRONT</text>';
    const units=[['Wren',142,230,'#8fb39b','bow',1],['Mara',close?320:268,169,'#8fb39b','shield',1],['Renn',broken?490:close?338:266,275,'#8fb39b','daggers',1],['Warden A',close?418:492,169,'#c9886c','shield',broken?0:1],['Warden B',close?415:492,275,'#c9886c','shield',broken?0:phase==='impact'?.45:1],['Archer',620,230,'#c9886c','bow',phase==='review'?0:1]];
    for(const[name,x,y,color,weapon,hp]of units){svg+=`<g opacity="${hp===0?.4:1}"><ellipse cx="${x}" cy="${y+8}" rx="30" ry="11" fill="${color}" stroke="#384d35"/>${person(x,y,color,1.2)}<text x="${x}" y="${y+31}" text-anchor="middle" font-size="12" fill="#233e32">${name}</text><rect x="${x-24}" y="${y-80}" width="48" height="4" fill="#686d4d"/><rect x="${x-24}" y="${y-80}" width="${48*hp}" height="4" fill="${color}"/>`;
      if(weapon==='shield')svg+=`<path d="M${x+13} ${y-38}l19 3 -3 25 -12 6 -7 -16Z" fill="#94a8a0" stroke="#e2d3a0" stroke-width="2"/>`;
      else if(weapon==='bow')svg+=`<path d="M${x+15} ${y-54}q30 25 0 52Z" fill="none" stroke="#735538" stroke-width="3"/>`;
      else svg+=`<path d="M${x-18} ${y-30}l-9 -24M${x+18} ${y-27}l12 -23" stroke="#d9e3d1" stroke-width="5"/>`;
      svg+='</g>';
    }
    if(phase==='engage')svg+='<path d="M182 203Q263 141 379 161" fill="none" stroke="#4e6c56" stroke-width="2" stroke-dasharray="5 7"/>';
    if(phase==='impact')svg+='<path d="M366 239l13 -13 2 19 17 -4 -10 15" fill="#f4d788" stroke="#a46e38"/><text x="380" y="304" text-anchor="middle" font-size="11" fill="#425e43">BLOCK / IMPACT</text>';
    if(broken)svg+='<path d="M457 88V325" stroke="#c1b086" stroke-width="7"/><text x="379" y="404" text-anchor="middle" class="scene-label">FRONT LINE BROKEN · REAR TARGETS NOW ELIGIBLE</text>';
    else svg+='<text x="379" y="404" text-anchor="middle" class="scene-label">LIVING FRONT LINE PROTECTS THE REAR</text>';
    $('battle-sketch').innerHTML=svg+'</svg>';
  }
  document.querySelectorAll('[data-battle]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-battle]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));battle(b.dataset.battle);}));
  renderRoom(); renderItem(); battle();
})();
