const fs=require('node:fs');const path=require('node:path');const P=require('../../progression');const target=path.resolve(__dirname,'../game-specification.md');let md=fs.readFileSync(target,'utf8').replace(/\r\n/g,'\n');const W=require('../../workshop');const data=W.apply(JSON.parse(JSON.stringify(require('../../data'))),P);let text='';for(const section of ['mine','forge','shop','adventurers','employees']){text+='### '+(section==='adventurers'?'Customers':section[0].toUpperCase()+section.slice(1))+' upgrade catalogue\n\n| Path | Upgrade | First cost | Ranks | Effect |\n|---|---|---|---|---|\n';for(const n of Object.values(P.nodes).filter(n=>n.section===section))text+=`| ${n.branch} | ${n.name} | ${n.cost} ${P.currencies[section]} | ${n.maxRank} | ${n.description} |\n`;text+='\n';}text+='### Smelter upgrade catalogue\n\n| Path | Upgrade | First cost | Ranks | Effect |\n|---|---|---|---|---|\n';for(const n of Object.values(W.upgrades))text+=`| ${n.branch} | ${n.name} | ${n.cost} Gold | ${n.maxRank} | ${n.description} |\n`;text+='\n### Permanent Legacy catalogue\n\n| Section | Talent | Sparks | Effect |\n|---|---|---|---|\n';for(const t of Object.values(data.talents).sort((a,b)=>a.branch.localeCompare(b.branch)||Number(!!b.legacySignature)-Number(!!a.legacySignature)||a.depth-b.depth))text+=`| ${t.branch} | ${t.name} | ${t.cost} | ${t.description} |\n`;text+='\n';const block='<!-- UPGRADE_CATALOGUE_START -->\n\n'+text+'<!-- UPGRADE_CATALOGUE_END -->';md=md.includes('<!-- UPGRADE_CATALOGUE_START -->')?md.replace(/<!-- UPGRADE_CATALOGUE_START -->[\s\S]*?<!-- UPGRADE_CATALOGUE_END -->/,block):md.replace('<!-- UPGRADE_CATALOGUE -->',block);fs.writeFileSync(target,md);console.log('Updated documentation with '+(Object.keys(P.nodes).length+Object.keys(W.upgrades).length)+' upgrade definitions.');

let catalogue='### Medieval patterns and item modifiers\n\nEvery row repeats across bronze, iron, steel, mithril and Starforged tiers. Material names describe the fantasy crafting tier, including fittings on composite weapons.\n\n| Item class | Training pattern | Standard pattern | Prestige pattern |\n|---|---|---|---|\n';
for(const c of Object.values(data.classes)){const family=Object.values(data.recipes).filter(r=>r.classId===c.id&&r.tier===1).sort((a,b)=>a.variant-b.variant);catalogue+=`| ${c.name} | ${family.map(r=>r.patternName).join(' | ')} |\n`;}
catalogue+='\nCrafted prefixes roll only on compatible slots and material tiers.\n\n| Crafted prefix | Effect | Slots | Minimum tier |\n|---|---|---|---|\n';
for(const a of Object.values(data.affixes))catalogue+=`| ${a.name} | ${a.description} | ${(a.slots||['all']).join(', ')} | ${a.minTier||1} |\n`;
catalogue+='\nEnchanting applies one chosen compatible suffix. Knowledge and upgrades strengthen its effect.\n\n| Enchanted suffix | Inscription | Effect | Gold fee | Catalysts |\n|---|---|---|---|---|\n';
for(const e of Object.values(data.enchantments))catalogue+=`| ${e.suffix} | ${e.name} | ${e.description} | ${e.cost} | ${Object.entries(e.inputs).map(([id,n])=>n+' '+data.materials[id].name).join(', ')} |\n`;
const itemBlock='<!-- ITEM_CATALOGUE_START -->\n\n'+catalogue+'\n<!-- ITEM_CATALOGUE_END -->\n\n';
md=md.includes('<!-- ITEM_CATALOGUE_START -->')?md.replace(/<!-- ITEM_CATALOGUE_START -->[\s\S]*?<!-- ITEM_CATALOGUE_END -->\n\n/,itemBlock):md.replace('### Machinery sequence',itemBlock+'### Machinery sequence');
fs.writeFileSync(target,md);console.log('Updated medieval pattern and modifier catalogue.');

let legacy='flowchart TB\n  ROOT["Defeat tier 5 boss and retire: 46–66 sparks"]\n';for(const branch of [...new Set(Object.values(data.talents).map(t=>t.branch))]){legacy+='  subgraph '+branch+'["'+branch+'"]\n';for(const t of Object.values(data.talents).filter(t=>t.branch===branch))legacy+='    '+t.id+'["'+t.name+' · '+t.cost+' sparks"]\n';legacy+='  end\n';}for(const t of Object.values(data.talents))legacy+='  '+(t.previousId||'ROOT')+' --> '+t.id+'\n';fs.writeFileSync(path.resolve(__dirname,'../diagrams/legacy-tree.mmd'),legacy);
